// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/generate-bindings.py from docs/derived-core-schema.json -- DO NOT EDIT.
// Machine-generated safe `Db` read accessors. include!()'d into lib.rs (unix only),
// so this file uses line comments (an inner //! doc is illegal mid-file).

impl Db {
    pub fn block_get_name(&self) -> String { sys::block_get_name(self.r()) }
    pub fn block_get_const_name(&self) -> String { sys::block_get_const_name(self.r()) }
    pub fn block_get_chip(&self) -> String { sys::block_get_chip(self.r()) }
    pub fn block_get_tech(&self) -> String { sys::block_get_tech(self.r()) }
    pub fn block_get_parent(&self) -> String { sys::block_get_parent(self.r()) }
    pub fn block_get_parent_inst(&self) -> String { sys::block_get_parent_inst(self.r()) }
    pub fn block_get_top_module(&self) -> String { sys::block_get_top_module(self.r()) }
    pub fn block_get_children(&self) -> Vec<String> { (0..sys::num_block_get_children(self.r())).map(|i| sys::nth_block_get_children(self.r(), i)).collect() }
    pub fn block_get_b_terms(&self) -> Vec<String> { (0..sys::num_block_get_b_terms(self.r())).map(|i| sys::nth_block_get_b_terms(self.r(), i)).collect() }
    pub fn block_get_i_terms(&self) -> Vec<String> { (0..sys::num_block_get_i_terms(self.r())).map(|i| sys::nth_block_get_i_terms(self.r(), i)).collect() }
    pub fn block_get_insts(&self) -> Vec<String> { (0..sys::num_block_get_insts(self.r())).map(|i| sys::nth_block_get_insts(self.r(), i)).collect() }
    pub fn block_get_modules(&self) -> Vec<String> { (0..sys::num_block_get_modules(self.r())).map(|i| sys::nth_block_get_modules(self.r(), i)).collect() }
    pub fn block_get_mod_insts(&self) -> Vec<String> { (0..sys::num_block_get_mod_insts(self.r())).map(|i| sys::nth_block_get_mod_insts(self.r(), i)).collect() }
    pub fn block_get_mod_nets(&self) -> Vec<String> { (0..sys::num_block_get_mod_nets(self.r())).map(|i| sys::nth_block_get_mod_nets(self.r(), i)).collect() }
    pub fn block_get_mod_b_terms(&self) -> Vec<String> { (0..sys::num_block_get_mod_b_terms(self.r())).map(|i| sys::nth_block_get_mod_b_terms(self.r(), i)).collect() }
    pub fn block_get_mod_i_terms(&self) -> Vec<String> { (0..sys::num_block_get_mod_i_terms(self.r())).map(|i| sys::nth_block_get_mod_i_terms(self.r(), i)).collect() }
    pub fn block_get_power_domains(&self) -> Vec<String> { (0..sys::num_block_get_power_domains(self.r())).map(|i| sys::nth_block_get_power_domains(self.r(), i)).collect() }
    pub fn block_get_logic_ports(&self) -> Vec<String> { (0..sys::num_block_get_logic_ports(self.r())).map(|i| sys::nth_block_get_logic_ports(self.r(), i)).collect() }
    pub fn block_get_power_switches(&self) -> Vec<String> { (0..sys::num_block_get_power_switches(self.r())).map(|i| sys::nth_block_get_power_switches(self.r(), i)).collect() }
    pub fn block_get_isolations(&self) -> Vec<String> { (0..sys::num_block_get_isolations(self.r())).map(|i| sys::nth_block_get_isolations(self.r(), i)).collect() }
    pub fn block_get_level_shifters(&self) -> Vec<String> { (0..sys::num_block_get_level_shifters(self.r())).map(|i| sys::nth_block_get_level_shifters(self.r(), i)).collect() }
    pub fn block_get_groups(&self) -> Vec<String> { (0..sys::num_block_get_groups(self.r())).map(|i| sys::nth_block_get_groups(self.r(), i)).collect() }
    pub fn block_get_component_mask_shift(&self) -> Vec<String> { (0..sys::num_block_get_component_mask_shift(self.r())).map(|i| sys::nth_block_get_component_mask_shift(self.r(), i)).collect() }
    pub fn block_get_nets(&self) -> Vec<String> { (0..sys::num_block_get_nets(self.r())).map(|i| sys::nth_block_get_nets(self.r(), i)).collect() }
    pub fn block_get_vias(&self) -> Vec<String> { (0..sys::num_block_get_vias(self.r())).map(|i| sys::nth_block_get_vias(self.r(), i)).collect() }
    pub fn block_get_def_units(&self) -> i32 { sys::block_get_def_units(self.r()) }
    pub fn block_get_db_units_per_micron(&self) -> i32 { sys::block_get_db_units_per_micron(self.r()) }
    pub fn block_get_corner_count(&self) -> i32 { sys::block_get_corner_count(self.r()) }
    pub fn block_get_corners_per_block(&self) -> i32 { sys::block_get_corners_per_block(self.r()) }
    pub fn block_get_ext_db_count(&self) -> i32 { sys::block_get_ext_db_count(self.r()) }
    pub fn block_get_corner_name_list(&self) -> String { sys::block_get_corner_name_list(self.r()) }
    pub fn block_get_rows(&self) -> Vec<String> { (0..sys::num_block_get_rows(self.r())).map(|i| sys::nth_block_get_rows(self.r(), i)).collect() }
    pub fn block_get_die_area_x_min(&self) -> i32 { sys::block_get_die_area_x_min(self.r()) }
    pub fn block_get_die_area_y_min(&self) -> i32 { sys::block_get_die_area_y_min(self.r()) }
    pub fn block_get_die_area_x_max(&self) -> i32 { sys::block_get_die_area_x_max(self.r()) }
    pub fn block_get_die_area_y_max(&self) -> i32 { sys::block_get_die_area_y_max(self.r()) }
    pub fn block_get_die_area_dx(&self) -> i32 { sys::block_get_die_area_dx(self.r()) }
    pub fn block_get_die_area_dy(&self) -> i32 { sys::block_get_die_area_dy(self.r()) }
    pub fn block_get_core_area_x_min(&self) -> i32 { sys::block_get_core_area_x_min(self.r()) }
    pub fn block_get_core_area_y_min(&self) -> i32 { sys::block_get_core_area_y_min(self.r()) }
    pub fn block_get_core_area_x_max(&self) -> i32 { sys::block_get_core_area_x_max(self.r()) }
    pub fn block_get_core_area_y_max(&self) -> i32 { sys::block_get_core_area_y_max(self.r()) }
    pub fn block_get_core_area_dx(&self) -> i32 { sys::block_get_core_area_dx(self.r()) }
    pub fn block_get_core_area_dy(&self) -> i32 { sys::block_get_core_area_dy(self.r()) }
    pub fn block_get_min_routing_layer(&self) -> i32 { sys::block_get_min_routing_layer(self.r()) }
    pub fn block_get_max_routing_layer(&self) -> i32 { sys::block_get_max_routing_layer(self.r()) }
    pub fn block_get_min_layer_for_clock(&self) -> i32 { sys::block_get_min_layer_for_clock(self.r()) }
    pub fn block_get_max_layer_for_clock(&self) -> i32 { sys::block_get_max_layer_for_clock(self.r()) }
    pub fn block_get_g_cell_tile_size(&self) -> i32 { sys::block_get_g_cell_tile_size(self.r()) }
    pub fn block_get_regions(&self) -> Vec<String> { (0..sys::num_block_get_regions(self.r())).map(|i| sys::nth_block_get_regions(self.r(), i)).collect() }
    pub fn block_get_non_default_rules(&self) -> Vec<String> { (0..sys::num_block_get_non_default_rules(self.r())).map(|i| sys::nth_block_get_non_default_rules(self.r(), i)).collect() }
    pub fn block_get_marker_categories(&self) -> Vec<String> { (0..sys::num_block_get_marker_categories(self.r())).map(|i| sys::nth_block_get_marker_categories(self.r(), i)).collect() }
    pub fn inst_get_name(&self, inst: &str) -> String { sys::inst_get_name(self.r(), inst) }
    pub fn inst_get_const_name(&self, inst: &str) -> String { sys::inst_get_const_name(self.r(), inst) }
    pub fn inst_get_origin_x(&self, inst: &str) -> i32 { sys::inst_get_origin_x(self.r(), inst) }
    pub fn inst_get_origin_y(&self, inst: &str) -> i32 { sys::inst_get_origin_y(self.r(), inst) }
    pub fn inst_get_orient(&self, inst: &str) -> String { sys::inst_get_orient(self.r(), inst) }
    pub fn inst_get_location_x(&self, inst: &str) -> i32 { sys::inst_get_location_x(self.r(), inst) }
    pub fn inst_get_location_y(&self, inst: &str) -> i32 { sys::inst_get_location_y(self.r(), inst) }
    pub fn inst_get_placement_status(&self, inst: &str) -> String { sys::inst_get_placement_status(self.r(), inst) }
    pub fn inst_is_fixed(&self, inst: &str) -> bool { sys::inst_is_fixed(self.r(), inst) }
    pub fn inst_is_placed(&self, inst: &str) -> bool { sys::inst_is_placed(self.r(), inst) }
    pub fn inst_get_eco_create(&self, inst: &str) -> bool { sys::inst_get_eco_create(self.r(), inst) }
    pub fn inst_get_eco_destroy(&self, inst: &str) -> bool { sys::inst_get_eco_destroy(self.r(), inst) }
    pub fn inst_get_eco_modify(&self, inst: &str) -> bool { sys::inst_get_eco_modify(self.r(), inst) }
    pub fn inst_get_user_flag1(&self, inst: &str) -> bool { sys::inst_get_user_flag1(self.r(), inst) }
    pub fn inst_get_user_flag2(&self, inst: &str) -> bool { sys::inst_get_user_flag2(self.r(), inst) }
    pub fn inst_get_user_flag3(&self, inst: &str) -> bool { sys::inst_get_user_flag3(self.r(), inst) }
    pub fn inst_is_do_not_touch(&self, inst: &str) -> bool { sys::inst_is_do_not_touch(self.r(), inst) }
    pub fn inst_get_block(&self, inst: &str) -> String { sys::inst_get_block(self.r(), inst) }
    pub fn inst_get_master(&self, inst: &str) -> String { sys::inst_get_master(self.r(), inst) }
    pub fn inst_get_group(&self, inst: &str) -> String { sys::inst_get_group(self.r(), inst) }
    pub fn inst_get_i_terms(&self, inst: &str) -> Vec<String> { (0..sys::num_inst_get_i_terms(self.r(), inst)).map(|i| sys::nth_inst_get_i_terms(self.r(), inst, i)).collect() }
    pub fn inst_get_first_input(&self, inst: &str) -> String { sys::inst_get_first_input(self.r(), inst) }
    pub fn inst_get_first_output(&self, inst: &str) -> String { sys::inst_get_first_output(self.r(), inst) }
    pub fn inst_get_region(&self, inst: &str) -> String { sys::inst_get_region(self.r(), inst) }
    pub fn inst_get_module(&self, inst: &str) -> String { sys::inst_get_module(self.r(), inst) }
    pub fn inst_get_child(&self, inst: &str) -> String { sys::inst_get_child(self.r(), inst) }
    pub fn inst_get_parent(&self, inst: &str) -> String { sys::inst_get_parent(self.r(), inst) }
    pub fn inst_get_children(&self, inst: &str) -> Vec<String> { (0..sys::num_inst_get_children(self.r(), inst)).map(|i| sys::nth_inst_get_children(self.r(), inst, i)).collect() }
    pub fn inst_is_hierarchical(&self, inst: &str) -> bool { sys::inst_is_hierarchical(self.r(), inst) }
    pub fn inst_is_physical_only(&self, inst: &str) -> bool { sys::inst_is_physical_only(self.r(), inst) }
    pub fn inst_get_transformed_halo_x_min(&self, inst: &str) -> i32 { sys::inst_get_transformed_halo_x_min(self.r(), inst) }
    pub fn inst_get_transformed_halo_y_min(&self, inst: &str) -> i32 { sys::inst_get_transformed_halo_y_min(self.r(), inst) }
    pub fn inst_get_transformed_halo_x_max(&self, inst: &str) -> i32 { sys::inst_get_transformed_halo_x_max(self.r(), inst) }
    pub fn inst_get_transformed_halo_y_max(&self, inst: &str) -> i32 { sys::inst_get_transformed_halo_y_max(self.r(), inst) }
    pub fn inst_get_transformed_halo_dx(&self, inst: &str) -> i32 { sys::inst_get_transformed_halo_dx(self.r(), inst) }
    pub fn inst_get_transformed_halo_dy(&self, inst: &str) -> i32 { sys::inst_get_transformed_halo_dy(self.r(), inst) }
    pub fn inst_get_weight(&self, inst: &str) -> i32 { sys::inst_get_weight(self.r(), inst) }
    pub fn inst_get_source_type(&self, inst: &str) -> String { sys::inst_get_source_type(self.r(), inst) }
    pub fn inst_is_block(&self, inst: &str) -> bool { sys::inst_is_block(self.r(), inst) }
    pub fn inst_is_core(&self, inst: &str) -> bool { sys::inst_is_core(self.r(), inst) }
    pub fn inst_is_pad(&self, inst: &str) -> bool { sys::inst_is_pad(self.r(), inst) }
    pub fn inst_is_end_cap(&self, inst: &str) -> bool { sys::inst_is_end_cap(self.r(), inst) }
    pub fn inst_get_pin_access_idx(&self, inst: &str) -> u32 { sys::inst_get_pin_access_idx(self.r(), inst) }
    pub fn net_get_name(&self, net: &str) -> String { sys::net_get_name(self.r(), net) }
    pub fn net_get_const_name(&self, net: &str) -> String { sys::net_get_const_name(self.r(), net) }
    pub fn net_is_r_c_disconnected(&self, net: &str) -> bool { sys::net_is_r_c_disconnected(self.r(), net) }
    pub fn net_get_weight(&self, net: &str) -> i32 { sys::net_get_weight(self.r(), net) }
    pub fn net_get_source_type(&self, net: &str) -> String { sys::net_get_source_type(self.r(), net) }
    pub fn net_get_x_talk_class(&self, net: &str) -> i32 { sys::net_get_x_talk_class(self.r(), net) }
    pub fn net_get_driving_i_term(&self, net: &str) -> String { sys::net_get_driving_i_term(self.r(), net) }
    pub fn net_has_fixed_bump(&self, net: &str) -> bool { sys::net_has_fixed_bump(self.r(), net) }
    pub fn net_get_wire_type(&self, net: &str) -> String { sys::net_get_wire_type(self.r(), net) }
    pub fn net_get_sig_type(&self, net: &str) -> String { sys::net_get_sig_type(self.r(), net) }
    pub fn net_is_marked(&self, net: &str) -> bool { sys::net_is_marked(self.r(), net) }
    pub fn net_is_mark_1ed(&self, net: &str) -> bool { sys::net_is_mark_1ed(self.r(), net) }
    pub fn net_is_select(&self, net: &str) -> bool { sys::net_is_select(self.r(), net) }
    pub fn net_is_wire_ordered(&self, net: &str) -> bool { sys::net_is_wire_ordered(self.r(), net) }
    pub fn net_is_disconnected(&self, net: &str) -> bool { sys::net_is_disconnected(self.r(), net) }
    pub fn net_is_wire_altered(&self, net: &str) -> bool { sys::net_is_wire_altered(self.r(), net) }
    pub fn net_is_r_cgraph(&self, net: &str) -> bool { sys::net_is_r_cgraph(self.r(), net) }
    pub fn net_is_extracted(&self, net: &str) -> bool { sys::net_is_extracted(self.r(), net) }
    pub fn net_is_spef(&self, net: &str) -> bool { sys::net_is_spef(self.r(), net) }
    pub fn net_is_do_not_touch(&self, net: &str) -> bool { sys::net_is_do_not_touch(self.r(), net) }
    pub fn net_get_block(&self, net: &str) -> String { sys::net_get_block(self.r(), net) }
    pub fn net_get_i_terms(&self, net: &str) -> Vec<String> { (0..sys::num_net_get_i_terms(self.r(), net)).map(|i| sys::nth_net_get_i_terms(self.r(), net, i)).collect() }
    pub fn net_get1st_i_term(&self, net: &str) -> String { sys::net_get1st_i_term(self.r(), net) }
    pub fn net_get_first_driver_inst(&self, net: &str) -> String { sys::net_get_first_driver_inst(self.r(), net) }
    pub fn net_get_first_output(&self, net: &str) -> String { sys::net_get_first_output(self.r(), net) }
    pub fn net_get_b_terms(&self, net: &str) -> Vec<String> { (0..sys::num_net_get_b_terms(self.r(), net)).map(|i| sys::nth_net_get_b_terms(self.r(), net, i)).collect() }
    pub fn net_get1st_b_term(&self, net: &str) -> String { sys::net_get1st_b_term(self.r(), net) }
    pub fn net_is_connected_by_abutment(&self, net: &str) -> bool { sys::net_is_connected_by_abutment(self.r(), net) }
    pub fn net_is_i_o(&self, net: &str) -> bool { sys::net_is_i_o(self.r(), net) }
    pub fn net_is_wild_connected(&self, net: &str) -> bool { sys::net_is_wild_connected(self.r(), net) }
    pub fn net_get_gndc_calib_factor(&self, net: &str) -> f32 { sys::net_get_gndc_calib_factor(self.r(), net) }
    pub fn net_get_cc_calib_factor(&self, net: &str) -> f32 { sys::net_get_cc_calib_factor(self.r(), net) }
    pub fn net_get_cc_adjust_factor(&self, net: &str) -> f32 { sys::net_get_cc_adjust_factor(self.r(), net) }
    pub fn net_get_cc_adjust_order(&self, net: &str) -> u32 { sys::net_get_cc_adjust_order(self.r(), net) }
    pub fn net_get_db_cc(&self, net: &str) -> f32 { sys::net_get_db_cc(self.r(), net) }
    pub fn net_get_ref_cc(&self, net: &str) -> f32 { sys::net_get_ref_cc(self.r(), net) }
    pub fn net_get_cc_match_ratio(&self, net: &str) -> f32 { sys::net_get_cc_match_ratio(self.r(), net) }
    pub fn net_get1st_r_seg_id(&self, net: &str) -> u32 { sys::net_get1st_r_seg_id(self.r(), net) }
    pub fn net_get1st_cap_node_id(&self, net: &str) -> u32 { sys::net_get1st_cap_node_id(self.r(), net) }
    pub fn net_get_r_seg_count(&self, net: &str) -> u32 { sys::net_get_r_seg_count(self.r(), net) }
    pub fn net_max_internal_cap_num(&self, net: &str) -> u32 { sys::net_max_internal_cap_num(self.r(), net) }
    pub fn net_get_cap_node_count(&self, net: &str) -> u32 { sys::net_get_cap_node_count(self.r(), net) }
    pub fn net_get_cc_count(&self, net: &str) -> u32 { sys::net_get_cc_count(self.r(), net) }
    pub fn net_get_non_default_rule(&self, net: &str) -> String { sys::net_get_non_default_rule(self.r(), net) }
    pub fn net_get_term_count(&self, net: &str) -> u32 { sys::net_get_term_count(self.r(), net) }
    pub fn net_get_i_term_count(&self, net: &str) -> u32 { sys::net_get_i_term_count(self.r(), net) }
    pub fn net_get_b_term_count(&self, net: &str) -> u32 { sys::net_get_b_term_count(self.r(), net) }
    pub fn net_get_term_b_box_x_min(&self, net: &str) -> i32 { sys::net_get_term_b_box_x_min(self.r(), net) }
    pub fn net_get_term_b_box_y_min(&self, net: &str) -> i32 { sys::net_get_term_b_box_y_min(self.r(), net) }
    pub fn net_get_term_b_box_x_max(&self, net: &str) -> i32 { sys::net_get_term_b_box_x_max(self.r(), net) }
    pub fn net_get_term_b_box_y_max(&self, net: &str) -> i32 { sys::net_get_term_b_box_y_max(self.r(), net) }
    pub fn net_get_term_b_box_dx(&self, net: &str) -> i32 { sys::net_get_term_b_box_dx(self.r(), net) }
    pub fn net_get_term_b_box_dy(&self, net: &str) -> i32 { sys::net_get_term_b_box_dy(self.r(), net) }
    pub fn net_find_main_parent_mod_inst(&self, net: &str) -> String { sys::net_find_main_parent_mod_inst(self.r(), net) }
    pub fn net_find_main_parent_module(&self, net: &str) -> String { sys::net_find_main_parent_module(self.r(), net) }
    pub fn net_has_jumpers(&self, net: &str) -> bool { sys::net_has_jumpers(self.r(), net) }
    pub fn net_find_mod_net_in_highest_hier(&self, net: &str) -> String { sys::net_find_mod_net_in_highest_hier(self.r(), net) }
    pub fn net_get_wire_count_wire_cnt(&self, net: &str) -> u32 { sys::net_get_wire_count_wire_cnt(self.r(), net) }
    pub fn net_get_wire_count_via_cnt(&self, net: &str) -> u32 { sys::net_get_wire_count_via_cnt(self.r(), net) }
    pub fn net_get_signal_wire_count_wire_cnt(&self, net: &str) -> u32 { sys::net_get_signal_wire_count_wire_cnt(self.r(), net) }
    pub fn net_get_signal_wire_count_via_cnt(&self, net: &str) -> u32 { sys::net_get_signal_wire_count_via_cnt(self.r(), net) }
    pub fn net_get_power_wire_count_wire_cnt(&self, net: &str) -> u32 { sys::net_get_power_wire_count_wire_cnt(self.r(), net) }
    pub fn net_get_power_wire_count_via_cnt(&self, net: &str) -> u32 { sys::net_get_power_wire_count_via_cnt(self.r(), net) }
    pub fn bterm_get_name(&self, bterm: &str) -> String { sys::bterm_get_name(self.r(), bterm) }
    pub fn bterm_get_const_name(&self, bterm: &str) -> String { sys::bterm_get_const_name(self.r(), bterm) }
    pub fn bterm_get_b_box_x_min(&self, bterm: &str) -> i32 { sys::bterm_get_b_box_x_min(self.r(), bterm) }
    pub fn bterm_get_b_box_y_min(&self, bterm: &str) -> i32 { sys::bterm_get_b_box_y_min(self.r(), bterm) }
    pub fn bterm_get_b_box_x_max(&self, bterm: &str) -> i32 { sys::bterm_get_b_box_x_max(self.r(), bterm) }
    pub fn bterm_get_b_box_y_max(&self, bterm: &str) -> i32 { sys::bterm_get_b_box_y_max(self.r(), bterm) }
    pub fn bterm_get_b_box_dx(&self, bterm: &str) -> i32 { sys::bterm_get_b_box_dx(self.r(), bterm) }
    pub fn bterm_get_b_box_dy(&self, bterm: &str) -> i32 { sys::bterm_get_b_box_dy(self.r(), bterm) }
    pub fn bterm_get_sig_type(&self, bterm: &str) -> String { sys::bterm_get_sig_type(self.r(), bterm) }
    pub fn bterm_get_io_type(&self, bterm: &str) -> String { sys::bterm_get_io_type(self.r(), bterm) }
    pub fn bterm_is_set_spef_mark(&self, bterm: &str) -> bool { sys::bterm_is_set_spef_mark(self.r(), bterm) }
    pub fn bterm_is_set_mark(&self, bterm: &str) -> bool { sys::bterm_is_set_mark(self.r(), bterm) }
    pub fn bterm_get_ext_id(&self, bterm: &str) -> u32 { sys::bterm_get_ext_id(self.r(), bterm) }
    pub fn bterm_is_special(&self, bterm: &str) -> bool { sys::bterm_is_special(self.r(), bterm) }
    pub fn bterm_get_net(&self, bterm: &str) -> String { sys::bterm_get_net(self.r(), bterm) }
    pub fn bterm_get_mod_net(&self, bterm: &str) -> String { sys::bterm_get_mod_net(self.r(), bterm) }
    pub fn bterm_get_block(&self, bterm: &str) -> String { sys::bterm_get_block(self.r(), bterm) }
    pub fn bterm_get_i_term(&self, bterm: &str) -> String { sys::bterm_get_i_term(self.r(), bterm) }
    pub fn bterm_get_first_pin_placement_status(&self, bterm: &str) -> String { sys::bterm_get_first_pin_placement_status(self.r(), bterm) }
    pub fn bterm_get_ground_pin(&self, bterm: &str) -> String { sys::bterm_get_ground_pin(self.r(), bterm) }
    pub fn bterm_get_supply_pin(&self, bterm: &str) -> String { sys::bterm_get_supply_pin(self.r(), bterm) }
    pub fn bterm_sta_vertex_id(&self, bterm: &str) -> u32 { sys::bterm_sta_vertex_id(self.r(), bterm) }
    pub fn bterm_get_mirrored_b_term(&self, bterm: &str) -> String { sys::bterm_get_mirrored_b_term(self.r(), bterm) }
    pub fn bterm_has_mirrored_b_term(&self, bterm: &str) -> bool { sys::bterm_has_mirrored_b_term(self.r(), bterm) }
    pub fn bterm_is_mirrored(&self, bterm: &str) -> bool { sys::bterm_is_mirrored(self.r(), bterm) }
    pub fn master_get_name(&self, master: &str) -> String { sys::master_get_name(self.r(), master) }
    pub fn master_get_const_name(&self, master: &str) -> String { sys::master_get_const_name(self.r(), master) }
    pub fn master_get_origin_x(&self, master: &str) -> i32 { sys::master_get_origin_x(self.r(), master) }
    pub fn master_get_origin_y(&self, master: &str) -> i32 { sys::master_get_origin_y(self.r(), master) }
    pub fn master_get_width(&self, master: &str) -> u32 { sys::master_get_width(self.r(), master) }
    pub fn master_get_height(&self, master: &str) -> u32 { sys::master_get_height(self.r(), master) }
    pub fn master_is_filler(&self, master: &str) -> bool { sys::master_is_filler(self.r(), master) }
    pub fn master_is_block(&self, master: &str) -> bool { sys::master_is_block(self.r(), master) }
    pub fn master_is_core(&self, master: &str) -> bool { sys::master_is_core(self.r(), master) }
    pub fn master_is_pad(&self, master: &str) -> bool { sys::master_is_pad(self.r(), master) }
    pub fn master_is_end_cap(&self, master: &str) -> bool { sys::master_is_end_cap(self.r(), master) }
    pub fn master_is_cover(&self, master: &str) -> bool { sys::master_is_cover(self.r(), master) }
    pub fn master_is_core_auto_placeable(&self, master: &str) -> bool { sys::master_is_core_auto_placeable(self.r(), master) }
    pub fn master_is_backside_bridge(&self, master: &str) -> bool { sys::master_is_backside_bridge(self.r(), master) }
    pub fn master_get_l_e_q(&self, master: &str) -> String { sys::master_get_l_e_q(self.r(), master) }
    pub fn master_get_e_e_q(&self, master: &str) -> String { sys::master_get_e_e_q(self.r(), master) }
    pub fn master_get_symmetry_x(&self, master: &str) -> bool { sys::master_get_symmetry_x(self.r(), master) }
    pub fn master_get_symmetry_y(&self, master: &str) -> bool { sys::master_get_symmetry_y(self.r(), master) }
    pub fn master_get_symmetry_r90(&self, master: &str) -> bool { sys::master_get_symmetry_r90(self.r(), master) }
    pub fn master_get_m_terms(&self, master: &str) -> Vec<String> { (0..sys::num_master_get_m_terms(self.r(), master)).map(|i| sys::nth_master_get_m_terms(self.r(), master, i)).collect() }
    pub fn master_get_lib(&self, master: &str) -> String { sys::master_get_lib(self.r(), master) }
    pub fn master_is_frozen(&self, master: &str) -> bool { sys::master_is_frozen(self.r(), master) }
    pub fn master_is_sequential(&self, master: &str) -> bool { sys::master_is_sequential(self.r(), master) }
    pub fn master_is_marked(&self, master: &str) -> u32 { sys::master_is_marked(self.r(), master) }
    pub fn master_is_special_power(&self, master: &str) -> bool { sys::master_is_special_power(self.r(), master) }
    pub fn master_get_m_term_count(&self, master: &str) -> i32 { sys::master_get_m_term_count(self.r(), master) }
    pub fn master_get_site(&self, master: &str) -> String { sys::master_get_site(self.r(), master) }
    pub fn master_get_master_id(&self, master: &str) -> i32 { sys::master_get_master_id(self.r(), master) }
    pub fn iterm_get_inst(&self, inst: &str, pin: &str) -> String { sys::iterm_get_inst(self.r(), inst, pin) }
    pub fn iterm_get_net(&self, inst: &str, pin: &str) -> String { sys::iterm_get_net(self.r(), inst, pin) }
    pub fn iterm_get_mod_net(&self, inst: &str, pin: &str) -> String { sys::iterm_get_mod_net(self.r(), inst, pin) }
    pub fn iterm_get_m_term(&self, inst: &str, pin: &str) -> String { sys::iterm_get_m_term(self.r(), inst, pin) }
    pub fn iterm_get_b_box_x_min(&self, inst: &str, pin: &str) -> i32 { sys::iterm_get_b_box_x_min(self.r(), inst, pin) }
    pub fn iterm_get_b_box_y_min(&self, inst: &str, pin: &str) -> i32 { sys::iterm_get_b_box_y_min(self.r(), inst, pin) }
    pub fn iterm_get_b_box_x_max(&self, inst: &str, pin: &str) -> i32 { sys::iterm_get_b_box_x_max(self.r(), inst, pin) }
    pub fn iterm_get_b_box_y_max(&self, inst: &str, pin: &str) -> i32 { sys::iterm_get_b_box_y_max(self.r(), inst, pin) }
    pub fn iterm_get_b_box_dx(&self, inst: &str, pin: &str) -> i32 { sys::iterm_get_b_box_dx(self.r(), inst, pin) }
    pub fn iterm_get_b_box_dy(&self, inst: &str, pin: &str) -> i32 { sys::iterm_get_b_box_dy(self.r(), inst, pin) }
    pub fn iterm_get_block(&self, inst: &str, pin: &str) -> String { sys::iterm_get_block(self.r(), inst, pin) }
    pub fn iterm_get_sig_type(&self, inst: &str, pin: &str) -> String { sys::iterm_get_sig_type(self.r(), inst, pin) }
    pub fn iterm_get_io_type(&self, inst: &str, pin: &str) -> String { sys::iterm_get_io_type(self.r(), inst, pin) }
    pub fn iterm_is_spef(&self, inst: &str, pin: &str) -> bool { sys::iterm_is_spef(self.r(), inst, pin) }
    pub fn iterm_get_ext_id(&self, inst: &str, pin: &str) -> u32 { sys::iterm_get_ext_id(self.r(), inst, pin) }
    pub fn iterm_is_special(&self, inst: &str, pin: &str) -> bool { sys::iterm_is_special(self.r(), inst, pin) }
    pub fn iterm_is_clocked(&self, inst: &str, pin: &str) -> bool { sys::iterm_is_clocked(self.r(), inst, pin) }
    pub fn iterm_is_set_mark(&self, inst: &str, pin: &str) -> bool { sys::iterm_is_set_mark(self.r(), inst, pin) }
    pub fn iterm_is_connected(&self, inst: &str, pin: &str) -> bool { sys::iterm_is_connected(self.r(), inst, pin) }
    pub fn iterm_get_b_term(&self, inst: &str, pin: &str) -> String { sys::iterm_get_b_term(self.r(), inst, pin) }
    pub fn iterm_sta_vertex_id(&self, inst: &str, pin: &str) -> u32 { sys::iterm_sta_vertex_id(self.r(), inst, pin) }
    pub fn mterm_get_name(&self, master: &str, term: &str) -> String { sys::mterm_get_name(self.r(), master, term) }
    pub fn mterm_get_const_name(&self, master: &str, term: &str) -> String { sys::mterm_get_const_name(self.r(), master, term) }
    pub fn mterm_get_sig_type(&self, master: &str, term: &str) -> String { sys::mterm_get_sig_type(self.r(), master, term) }
    pub fn mterm_get_io_type(&self, master: &str, term: &str) -> String { sys::mterm_get_io_type(self.r(), master, term) }
    pub fn mterm_is_set_mark(&self, master: &str, term: &str) -> bool { sys::mterm_is_set_mark(self.r(), master, term) }
    pub fn mterm_get_master(&self, master: &str, term: &str) -> String { sys::mterm_get_master(self.r(), master, term) }
    pub fn mterm_get_b_box_x_min(&self, master: &str, term: &str) -> i32 { sys::mterm_get_b_box_x_min(self.r(), master, term) }
    pub fn mterm_get_b_box_y_min(&self, master: &str, term: &str) -> i32 { sys::mterm_get_b_box_y_min(self.r(), master, term) }
    pub fn mterm_get_b_box_x_max(&self, master: &str, term: &str) -> i32 { sys::mterm_get_b_box_x_max(self.r(), master, term) }
    pub fn mterm_get_b_box_y_max(&self, master: &str, term: &str) -> i32 { sys::mterm_get_b_box_y_max(self.r(), master, term) }
    pub fn mterm_get_b_box_dx(&self, master: &str, term: &str) -> i32 { sys::mterm_get_b_box_dx(self.r(), master, term) }
    pub fn mterm_get_b_box_dy(&self, master: &str, term: &str) -> i32 { sys::mterm_get_b_box_dy(self.r(), master, term) }
    pub fn mterm_has_default_antenna_model(&self, master: &str, term: &str) -> bool { sys::mterm_has_default_antenna_model(self.r(), master, term) }
    pub fn mterm_has_oxide2_antenna_model(&self, master: &str, term: &str) -> bool { sys::mterm_has_oxide2_antenna_model(self.r(), master, term) }
    pub fn mterm_get_index(&self, master: &str, term: &str) -> i32 { sys::mterm_get_index(self.r(), master, term) }
    pub fn layer_get_wrong_way_width(&self, layer: &str) -> u32 { sys::layer_get_wrong_way_width(self.r(), layer) }
    pub fn layer_get_wrong_way_min_width(&self, layer: &str) -> u32 { sys::layer_get_wrong_way_min_width(self.r(), layer) }
    pub fn layer_get_layer_adjustment(&self, layer: &str) -> f32 { sys::layer_get_layer_adjustment(self.r(), layer) }
    pub fn layer_get_tech_layer_cut_class_rules(&self, layer: &str) -> Vec<String> { (0..sys::num_layer_get_tech_layer_cut_class_rules(self.r(), layer)).map(|i| sys::nth_layer_get_tech_layer_cut_class_rules(self.r(), layer, i)).collect() }
    pub fn layer_is_rect_only(&self, layer: &str) -> bool { sys::layer_is_rect_only(self.r(), layer) }
    pub fn layer_is_right_way_on_grid_only(&self, layer: &str) -> bool { sys::layer_is_right_way_on_grid_only(self.r(), layer) }
    pub fn layer_is_right_way_on_grid_only_check_mask(&self, layer: &str) -> bool { sys::layer_is_right_way_on_grid_only_check_mask(self.r(), layer) }
    pub fn layer_is_rect_only_except_non_core_pins(&self, layer: &str) -> bool { sys::layer_is_rect_only_except_non_core_pins(self.r(), layer) }
    pub fn layer_get_lef58_type_string(&self, layer: &str) -> String { sys::layer_get_lef58_type_string(self.r(), layer) }
    pub fn layer_is_backside(&self, layer: &str) -> bool { sys::layer_is_backside(self.r(), layer) }
    pub fn layer_get_name(&self, layer: &str) -> String { sys::layer_get_name(self.r(), layer) }
    pub fn layer_get_const_name(&self, layer: &str) -> String { sys::layer_get_const_name(self.r(), layer) }
    pub fn layer_has_alias(&self, layer: &str) -> bool { sys::layer_has_alias(self.r(), layer) }
    pub fn layer_get_alias(&self, layer: &str) -> String { sys::layer_get_alias(self.r(), layer) }
    pub fn layer_get_width(&self, layer: &str) -> u32 { sys::layer_get_width(self.r(), layer) }
    pub fn layer_get_spacing(&self, layer: &str) -> i32 { sys::layer_get_spacing(self.r(), layer) }
    pub fn layer_get_num_masks(&self, layer: &str) -> u32 { sys::layer_get_num_masks(self.r(), layer) }
    pub fn layer_has_v55_spacing_rules(&self, layer: &str) -> bool { sys::layer_has_v55_spacing_rules(self.r(), layer) }
    pub fn layer_has_two_widths_spacing_rules(&self, layer: &str) -> bool { sys::layer_has_two_widths_spacing_rules(self.r(), layer) }
    pub fn layer_get_two_widths_spacing_table_num_widths(&self, layer: &str) -> u32 { sys::layer_get_two_widths_spacing_table_num_widths(self.r(), layer) }
    pub fn layer_has_default_antenna_rule(&self, layer: &str) -> bool { sys::layer_has_default_antenna_rule(self.r(), layer) }
    pub fn layer_has_oxide2_antenna_rule(&self, layer: &str) -> bool { sys::layer_has_oxide2_antenna_rule(self.r(), layer) }
    pub fn layer_get_pitch(&self, layer: &str) -> i32 { sys::layer_get_pitch(self.r(), layer) }
    pub fn layer_get_pitch_x(&self, layer: &str) -> i32 { sys::layer_get_pitch_x(self.r(), layer) }
    pub fn layer_get_pitch_y(&self, layer: &str) -> i32 { sys::layer_get_pitch_y(self.r(), layer) }
    pub fn layer_get_first_last_pitch(&self, layer: &str) -> i32 { sys::layer_get_first_last_pitch(self.r(), layer) }
    pub fn layer_has_x_y_pitch(&self, layer: &str) -> bool { sys::layer_has_x_y_pitch(self.r(), layer) }
    pub fn layer_get_offset(&self, layer: &str) -> i32 { sys::layer_get_offset(self.r(), layer) }
    pub fn layer_get_offset_x(&self, layer: &str) -> i32 { sys::layer_get_offset_x(self.r(), layer) }
    pub fn layer_get_offset_y(&self, layer: &str) -> i32 { sys::layer_get_offset_y(self.r(), layer) }
    pub fn layer_has_x_y_offset(&self, layer: &str) -> bool { sys::layer_has_x_y_offset(self.r(), layer) }
    pub fn layer_has_area(&self, layer: &str) -> bool { sys::layer_has_area(self.r(), layer) }
    pub fn layer_has_max_width(&self, layer: &str) -> bool { sys::layer_has_max_width(self.r(), layer) }
    pub fn layer_get_max_width(&self, layer: &str) -> u32 { sys::layer_get_max_width(self.r(), layer) }
    pub fn layer_get_min_width(&self, layer: &str) -> u32 { sys::layer_get_min_width(self.r(), layer) }
    pub fn layer_has_min_step(&self, layer: &str) -> bool { sys::layer_has_min_step(self.r(), layer) }
    pub fn layer_get_min_step(&self, layer: &str) -> u32 { sys::layer_get_min_step(self.r(), layer) }
    pub fn layer_has_min_step_max_length(&self, layer: &str) -> bool { sys::layer_has_min_step_max_length(self.r(), layer) }
    pub fn layer_get_min_step_max_length(&self, layer: &str) -> u32 { sys::layer_get_min_step_max_length(self.r(), layer) }
    pub fn layer_has_min_step_max_edges(&self, layer: &str) -> bool { sys::layer_has_min_step_max_edges(self.r(), layer) }
    pub fn layer_get_min_step_max_edges(&self, layer: &str) -> u32 { sys::layer_get_min_step_max_edges(self.r(), layer) }
    pub fn layer_has_protrusion(&self, layer: &str) -> bool { sys::layer_has_protrusion(self.r(), layer) }
    pub fn layer_get_protrusion_width(&self, layer: &str) -> u32 { sys::layer_get_protrusion_width(self.r(), layer) }
    pub fn layer_get_protrusion_length(&self, layer: &str) -> u32 { sys::layer_get_protrusion_length(self.r(), layer) }
    pub fn layer_get_protrusion_from_width(&self, layer: &str) -> u32 { sys::layer_get_protrusion_from_width(self.r(), layer) }
    pub fn layer_get_resistance(&self, layer: &str) -> f64 { sys::layer_get_resistance(self.r(), layer) }
    pub fn layer_get_capacitance(&self, layer: &str) -> f64 { sys::layer_get_capacitance(self.r(), layer) }
    pub fn layer_get_edge_capacitance(&self, layer: &str) -> f64 { sys::layer_get_edge_capacitance(self.r(), layer) }
    pub fn layer_get_wire_extension(&self, layer: &str) -> u32 { sys::layer_get_wire_extension(self.r(), layer) }
    pub fn layer_get_number(&self, layer: &str) -> i32 { sys::layer_get_number(self.r(), layer) }
    pub fn layer_get_routing_level(&self, layer: &str) -> i32 { sys::layer_get_routing_level(self.r(), layer) }
    pub fn layer_get_lower_layer(&self, layer: &str) -> String { sys::layer_get_lower_layer(self.r(), layer) }
    pub fn layer_get_upper_layer(&self, layer: &str) -> String { sys::layer_get_upper_layer(self.r(), layer) }
    pub fn layer_get_tech(&self, layer: &str) -> String { sys::layer_get_tech(self.r(), layer) }
    pub fn layer_has_orth_spacing_table(&self, layer: &str) -> bool { sys::layer_has_orth_spacing_table(self.r(), layer) }
    pub fn layer_get_max_wide_d_r_c_range_owidth(&self, layer: &str) -> i32 { sys::layer_get_max_wide_d_r_c_range_owidth(self.r(), layer) }
    pub fn layer_get_max_wide_d_r_c_range_olength(&self, layer: &str) -> i32 { sys::layer_get_max_wide_d_r_c_range_olength(self.r(), layer) }
    pub fn layer_get_min_wide_d_r_c_range_owidth(&self, layer: &str) -> i32 { sys::layer_get_min_wide_d_r_c_range_owidth(self.r(), layer) }
    pub fn layer_get_min_wide_d_r_c_range_olength(&self, layer: &str) -> i32 { sys::layer_get_min_wide_d_r_c_range_olength(self.r(), layer) }
    pub fn row_get_name(&self, row: &str) -> String { sys::row_get_name(self.r(), row) }
    pub fn row_get_const_name(&self, row: &str) -> String { sys::row_get_const_name(self.r(), row) }
    pub fn row_get_site(&self, row: &str) -> String { sys::row_get_site(self.r(), row) }
    pub fn row_get_origin_x(&self, row: &str) -> i32 { sys::row_get_origin_x(self.r(), row) }
    pub fn row_get_origin_y(&self, row: &str) -> i32 { sys::row_get_origin_y(self.r(), row) }
    pub fn row_get_orient(&self, row: &str) -> String { sys::row_get_orient(self.r(), row) }
    pub fn row_get_site_count(&self, row: &str) -> i32 { sys::row_get_site_count(self.r(), row) }
    pub fn row_get_spacing(&self, row: &str) -> i32 { sys::row_get_spacing(self.r(), row) }
    pub fn row_get_b_box_x_min(&self, row: &str) -> i32 { sys::row_get_b_box_x_min(self.r(), row) }
    pub fn row_get_b_box_y_min(&self, row: &str) -> i32 { sys::row_get_b_box_y_min(self.r(), row) }
    pub fn row_get_b_box_x_max(&self, row: &str) -> i32 { sys::row_get_b_box_x_max(self.r(), row) }
    pub fn row_get_b_box_y_max(&self, row: &str) -> i32 { sys::row_get_b_box_y_max(self.r(), row) }
    pub fn row_get_b_box_dx(&self, row: &str) -> i32 { sys::row_get_b_box_dx(self.r(), row) }
    pub fn row_get_b_box_dy(&self, row: &str) -> i32 { sys::row_get_b_box_dy(self.r(), row) }
    pub fn row_get_block(&self, row: &str) -> String { sys::row_get_block(self.r(), row) }
    pub fn via_get_name(&self, via: &str) -> String { sys::via_get_name(self.r(), via) }
    pub fn via_get_const_name(&self, via: &str) -> String { sys::via_get_const_name(self.r(), via) }
    pub fn via_get_pattern(&self, via: &str) -> String { sys::via_get_pattern(self.r(), via) }
    pub fn via_get_via_generate_rule(&self, via: &str) -> String { sys::via_get_via_generate_rule(self.r(), via) }
    pub fn via_has_params(&self, via: &str) -> bool { sys::via_has_params(self.r(), via) }
    pub fn via_get_block(&self, via: &str) -> String { sys::via_get_block(self.r(), via) }
    pub fn via_get_top_layer(&self, via: &str) -> String { sys::via_get_top_layer(self.r(), via) }
    pub fn via_get_bottom_layer(&self, via: &str) -> String { sys::via_get_bottom_layer(self.r(), via) }
    pub fn via_is_via_rotated(&self, via: &str) -> bool { sys::via_is_via_rotated(self.r(), via) }
    pub fn via_get_orient(&self, via: &str) -> String { sys::via_get_orient(self.r(), via) }
    pub fn via_get_tech_via(&self, via: &str) -> String { sys::via_get_tech_via(self.r(), via) }
    pub fn via_get_block_via(&self, via: &str) -> String { sys::via_get_block_via(self.r(), via) }
    pub fn via_is_default(&self, via: &str) -> bool { sys::via_is_default(self.r(), via) }
    pub fn techvia_get_name(&self, via: &str) -> String { sys::techvia_get_name(self.r(), via) }
    pub fn techvia_get_const_name(&self, via: &str) -> String { sys::techvia_get_const_name(self.r(), via) }
    pub fn techvia_is_default(&self, via: &str) -> bool { sys::techvia_is_default(self.r(), via) }
    pub fn techvia_is_top_of_stack(&self, via: &str) -> bool { sys::techvia_is_top_of_stack(self.r(), via) }
    pub fn techvia_get_resistance(&self, via: &str) -> f64 { sys::techvia_get_resistance(self.r(), via) }
    pub fn techvia_get_pattern(&self, via: &str) -> String { sys::techvia_get_pattern(self.r(), via) }
    pub fn techvia_get_via_generate_rule(&self, via: &str) -> String { sys::techvia_get_via_generate_rule(self.r(), via) }
    pub fn techvia_has_params(&self, via: &str) -> bool { sys::techvia_has_params(self.r(), via) }
    pub fn techvia_get_tech(&self, via: &str) -> String { sys::techvia_get_tech(self.r(), via) }
    pub fn techvia_get_top_layer(&self, via: &str) -> String { sys::techvia_get_top_layer(self.r(), via) }
    pub fn techvia_get_bottom_layer(&self, via: &str) -> String { sys::techvia_get_bottom_layer(self.r(), via) }
    pub fn techvia_get_non_default_rule(&self, via: &str) -> String { sys::techvia_get_non_default_rule(self.r(), via) }
    pub fn ndr_get_name(&self, rule: &str) -> String { sys::ndr_get_name(self.r(), rule) }
    pub fn ndr_get_const_name(&self, rule: &str) -> String { sys::ndr_get_const_name(self.r(), rule) }
    pub fn ndr_is_block_rule(&self, rule: &str) -> bool { sys::ndr_is_block_rule(self.r(), rule) }
    pub fn ndr_get_hard_spacing(&self, rule: &str) -> bool { sys::ndr_get_hard_spacing(self.r(), rule) }
    pub fn site_get_name(&self, site: &str) -> String { sys::site_get_name(self.r(), site) }
    pub fn site_get_const_name(&self, site: &str) -> String { sys::site_get_const_name(self.r(), site) }
    pub fn site_get_width(&self, site: &str) -> i32 { sys::site_get_width(self.r(), site) }
    pub fn site_get_height(&self, site: &str) -> i32 { sys::site_get_height(self.r(), site) }
    pub fn site_get_symmetry_x(&self, site: &str) -> bool { sys::site_get_symmetry_x(self.r(), site) }
    pub fn site_get_symmetry_y(&self, site: &str) -> bool { sys::site_get_symmetry_y(self.r(), site) }
    pub fn site_get_symmetry_r90(&self, site: &str) -> bool { sys::site_get_symmetry_r90(self.r(), site) }
    pub fn site_has_row_pattern(&self, site: &str) -> bool { sys::site_has_row_pattern(self.r(), site) }
    pub fn site_is_hybrid(&self, site: &str) -> bool { sys::site_is_hybrid(self.r(), site) }
    pub fn site_get_lib(&self, site: &str) -> String { sys::site_get_lib(self.r(), site) }
    pub fn obs_get_instance(&self, idx: usize) -> String { sys::obs_get_instance(self.r(), idx) }
    pub fn obs_is_slot_obstruction(&self, idx: usize) -> bool { sys::obs_is_slot_obstruction(self.r(), idx) }
    pub fn obs_is_fill_obstruction(&self, idx: usize) -> bool { sys::obs_is_fill_obstruction(self.r(), idx) }
    pub fn obs_is_except_p_g_nets_obstruction(&self, idx: usize) -> bool { sys::obs_is_except_p_g_nets_obstruction(self.r(), idx) }
    pub fn obs_is_pushed_down(&self, idx: usize) -> bool { sys::obs_is_pushed_down(self.r(), idx) }
    pub fn obs_has_effective_width(&self, idx: usize) -> bool { sys::obs_has_effective_width(self.r(), idx) }
    pub fn obs_get_effective_width(&self, idx: usize) -> i32 { sys::obs_get_effective_width(self.r(), idx) }
    pub fn obs_has_min_spacing(&self, idx: usize) -> bool { sys::obs_has_min_spacing(self.r(), idx) }
    pub fn obs_get_min_spacing(&self, idx: usize) -> i32 { sys::obs_get_min_spacing(self.r(), idx) }
    pub fn obs_get_block(&self, idx: usize) -> String { sys::obs_get_block(self.r(), idx) }
    pub fn obs_is_system_reserved(&self, idx: usize) -> bool { sys::obs_is_system_reserved(self.r(), idx) }
    pub fn swire_get_block(&self, net: &str, idx: usize) -> String { sys::swire_get_block(self.r(), net, idx) }
    pub fn swire_get_net(&self, net: &str, idx: usize) -> String { sys::swire_get_net(self.r(), net, idx) }
    pub fn swire_get_wire_type(&self, net: &str, idx: usize) -> String { sys::swire_get_wire_type(self.r(), net, idx) }
    pub fn swire_get_shield(&self, net: &str, idx: usize) -> String { sys::swire_get_shield(self.r(), net, idx) }
    pub fn wire_get_block(&self, net: &str) -> String { sys::wire_get_block(self.r(), net) }
    pub fn wire_get_net(&self, net: &str) -> String { sys::wire_get_net(self.r(), net) }
    pub fn wire_is_global_wire(&self, net: &str) -> bool { sys::wire_is_global_wire(self.r(), net) }
    pub fn wire_length(&self, net: &str) -> u32 { sys::wire_length(self.r(), net) }
    pub fn wire_count(&self, net: &str) -> u32 { sys::wire_count(self.r(), net) }
    pub fn fill_needs_o_p_c(&self, idx: usize) -> bool { sys::fill_needs_o_p_c(self.r(), idx) }
    pub fn fill_mask_number(&self, idx: usize) -> u32 { sys::fill_mask_number(self.r(), idx) }
    pub fn fill_get_tech_layer(&self, idx: usize) -> String { sys::fill_get_tech_layer(self.r(), idx) }
    pub fn box_x_min(&self, idx: usize) -> i32 { sys::box_x_min(self.r(), idx) }
    pub fn box_y_min(&self, idx: usize) -> i32 { sys::box_y_min(self.r(), idx) }
    pub fn box_x_max(&self, idx: usize) -> i32 { sys::box_x_max(self.r(), idx) }
    pub fn box_y_max(&self, idx: usize) -> i32 { sys::box_y_max(self.r(), idx) }
    pub fn box_is_via(&self, idx: usize) -> bool { sys::box_is_via(self.r(), idx) }
    pub fn box_get_tech_via(&self, idx: usize) -> String { sys::box_get_tech_via(self.r(), idx) }
    pub fn box_get_block_via(&self, idx: usize) -> String { sys::box_get_block_via(self.r(), idx) }
    pub fn box_get_via_x_y_x(&self, idx: usize) -> i32 { sys::box_get_via_x_y_x(self.r(), idx) }
    pub fn box_get_via_x_y_y(&self, idx: usize) -> i32 { sys::box_get_via_x_y_y(self.r(), idx) }
    pub fn box_get_box_x_min(&self, idx: usize) -> i32 { sys::box_get_box_x_min(self.r(), idx) }
    pub fn box_get_box_y_min(&self, idx: usize) -> i32 { sys::box_get_box_y_min(self.r(), idx) }
    pub fn box_get_box_x_max(&self, idx: usize) -> i32 { sys::box_get_box_x_max(self.r(), idx) }
    pub fn box_get_box_y_max(&self, idx: usize) -> i32 { sys::box_get_box_y_max(self.r(), idx) }
    pub fn box_get_box_dx(&self, idx: usize) -> i32 { sys::box_get_box_dx(self.r(), idx) }
    pub fn box_get_box_dy(&self, idx: usize) -> i32 { sys::box_get_box_dy(self.r(), idx) }
    pub fn box_get_d_x(&self, idx: usize) -> u32 { sys::box_get_d_x(self.r(), idx) }
    pub fn box_get_design_rule_width(&self, idx: usize) -> i32 { sys::box_get_design_rule_width(self.r(), idx) }
    pub fn box_get_d_y(&self, idx: usize) -> u32 { sys::box_get_d_y(self.r(), idx) }
    pub fn box_is_soft(&self, idx: usize) -> bool { sys::box_is_soft(self.r(), idx) }
    pub fn box_get_tech_layer(&self, idx: usize) -> String { sys::box_get_tech_layer(self.r(), idx) }
    pub fn box_get_layer_mask(&self, idx: usize) -> u32 { sys::box_get_layer_mask(self.r(), idx) }
    pub fn module_get_name(&self, module: &str) -> String { sys::module_get_name(self.r(), module) }
    pub fn module_get_mod_inst(&self, module: &str) -> String { sys::module_get_mod_inst(self.r(), module) }
    pub fn module_get_parent_module(&self, module: &str) -> String { sys::module_get_parent_module(self.r(), module) }
    pub fn module_get_hierarchical_name(&self, module: &str) -> String { sys::module_get_hierarchical_name(self.r(), module) }
    pub fn module_get_owner(&self, module: &str) -> String { sys::module_get_owner(self.r(), module) }
    pub fn module_get_children(&self, module: &str) -> Vec<String> { (0..sys::num_module_get_children(self.r(), module)).map(|i| sys::nth_module_get_children(self.r(), module, i)).collect() }
    pub fn module_get_mod_insts(&self, module: &str) -> Vec<String> { (0..sys::num_module_get_mod_insts(self.r(), module)).map(|i| sys::nth_module_get_mod_insts(self.r(), module, i)).collect() }
    pub fn module_get_mod_nets(&self, module: &str) -> Vec<String> { (0..sys::num_module_get_mod_nets(self.r(), module)).map(|i| sys::nth_module_get_mod_nets(self.r(), module, i)).collect() }
    pub fn module_get_ports(&self, module: &str) -> Vec<String> { (0..sys::num_module_get_ports(self.r(), module)).map(|i| sys::nth_module_get_ports(self.r(), module, i)).collect() }
    pub fn module_get_mod_b_terms(&self, module: &str) -> Vec<String> { (0..sys::num_module_get_mod_b_terms(self.r(), module)).map(|i| sys::nth_module_get_mod_b_terms(self.r(), module, i)).collect() }
    pub fn module_get_insts(&self, module: &str) -> Vec<String> { (0..sys::num_module_get_insts(self.r(), module)).map(|i| sys::nth_module_get_insts(self.r(), module, i)).collect() }
    pub fn module_get_leaf_insts(&self, module: &str) -> Vec<String> { (0..sys::num_module_get_leaf_insts(self.r(), module)).map(|i| sys::nth_module_get_leaf_insts(self.r(), module, i)).collect() }
    pub fn module_get_mod_inst_count(&self, module: &str) -> i32 { sys::module_get_mod_inst_count(self.r(), module) }
    pub fn module_get_db_inst_count(&self, module: &str) -> i32 { sys::module_get_db_inst_count(self.r(), module) }
    pub fn module_is_top(&self, module: &str) -> bool { sys::module_is_top(self.r(), module) }
    pub fn group_get_name(&self, group: &str) -> String { sys::group_get_name(self.r(), group) }
    pub fn group_get_parent_group(&self, group: &str) -> String { sys::group_get_parent_group(self.r(), group) }
    pub fn group_get_region(&self, group: &str) -> String { sys::group_get_region(self.r(), group) }
    pub fn group_get_mod_insts(&self, group: &str) -> Vec<String> { (0..sys::num_group_get_mod_insts(self.r(), group)).map(|i| sys::nth_group_get_mod_insts(self.r(), group, i)).collect() }
    pub fn group_get_insts(&self, group: &str) -> Vec<String> { (0..sys::num_group_get_insts(self.r(), group)).map(|i| sys::nth_group_get_insts(self.r(), group, i)).collect() }
    pub fn group_get_groups(&self, group: &str) -> Vec<String> { (0..sys::num_group_get_groups(self.r(), group)).map(|i| sys::nth_group_get_groups(self.r(), group, i)).collect() }
    pub fn group_get_power_nets(&self, group: &str) -> Vec<String> { (0..sys::num_group_get_power_nets(self.r(), group)).map(|i| sys::nth_group_get_power_nets(self.r(), group, i)).collect() }
    pub fn group_get_ground_nets(&self, group: &str) -> Vec<String> { (0..sys::num_group_get_ground_nets(self.r(), group)).map(|i| sys::nth_group_get_ground_nets(self.r(), group, i)).collect() }
    pub fn region_get_name(&self, region: &str) -> String { sys::region_get_name(self.r(), region) }
    pub fn region_get_region_insts(&self, region: &str) -> Vec<String> { (0..sys::num_region_get_region_insts(self.r(), region)).map(|i| sys::nth_region_get_region_insts(self.r(), region, i)).collect() }
    pub fn region_is_invalid(&self, region: &str) -> bool { sys::region_is_invalid(self.r(), region) }
    pub fn region_get_groups(&self, region: &str) -> Vec<String> { (0..sys::num_region_get_groups(self.r(), region)).map(|i| sys::nth_region_get_groups(self.r(), region, i)).collect() }
    pub fn region_get_block(&self, region: &str) -> String { sys::region_get_block(self.r(), region) }
    pub fn blockage_get_instance(&self, idx: usize) -> String { sys::blockage_get_instance(self.r(), idx) }
    pub fn blockage_is_pushed_down(&self, idx: usize) -> bool { sys::blockage_is_pushed_down(self.r(), idx) }
    pub fn blockage_is_soft(&self, idx: usize) -> bool { sys::blockage_is_soft(self.r(), idx) }
    pub fn blockage_is_system_reserved(&self, idx: usize) -> bool { sys::blockage_is_system_reserved(self.r(), idx) }
    pub fn blockage_get_max_density(&self, idx: usize) -> f32 { sys::blockage_get_max_density(self.r(), idx) }
    pub fn blockage_get_block(&self, idx: usize) -> String { sys::blockage_get_block(self.r(), idx) }
    pub fn trackgrid_get_tech_layer(&self, idx: usize) -> String { sys::trackgrid_get_tech_layer(self.r(), idx) }
    pub fn trackgrid_get_block(&self, idx: usize) -> String { sys::trackgrid_get_block(self.r(), idx) }
    pub fn trackgrid_get_num_grid_patterns_x(&self, idx: usize) -> i32 { sys::trackgrid_get_num_grid_patterns_x(self.r(), idx) }
    pub fn trackgrid_get_num_grid_patterns_y(&self, idx: usize) -> i32 { sys::trackgrid_get_num_grid_patterns_y(self.r(), idx) }
    pub fn marker_cat_get_name(&self, category: &str) -> String { sys::marker_cat_get_name(self.r(), category) }
    pub fn marker_cat_get_description(&self, category: &str) -> String { sys::marker_cat_get_description(self.r(), category) }
    pub fn marker_cat_get_max_markers(&self, category: &str) -> i32 { sys::marker_cat_get_max_markers(self.r(), category) }
    pub fn marker_cat_get_markers(&self, category: &str) -> Vec<String> { (0..sys::num_marker_cat_get_markers(self.r(), category)).map(|i| sys::nth_marker_cat_get_markers(self.r(), category, i)).collect() }
    pub fn marker_cat_get_marker_categories(&self, category: &str) -> Vec<String> { (0..sys::num_marker_cat_get_marker_categories(self.r(), category)).map(|i| sys::nth_marker_cat_get_marker_categories(self.r(), category, i)).collect() }
    pub fn marker_cat_get_top_category(&self, category: &str) -> String { sys::marker_cat_get_top_category(self.r(), category) }
    pub fn marker_cat_get_source(&self, category: &str) -> String { sys::marker_cat_get_source(self.r(), category) }
    pub fn marker_cat_get_marker_count(&self, category: &str) -> i32 { sys::marker_cat_get_marker_count(self.r(), category) }
    pub fn marker_get_comment(&self, category: &str, idx: usize) -> String { sys::marker_get_comment(self.r(), category, idx) }
    pub fn marker_get_line_number(&self, category: &str, idx: usize) -> i32 { sys::marker_get_line_number(self.r(), category, idx) }
    pub fn marker_is_visited(&self, category: &str, idx: usize) -> bool { sys::marker_is_visited(self.r(), category, idx) }
    pub fn marker_is_visible(&self, category: &str, idx: usize) -> bool { sys::marker_is_visible(self.r(), category, idx) }
    pub fn marker_is_waived(&self, category: &str, idx: usize) -> bool { sys::marker_is_waived(self.r(), category, idx) }
    pub fn marker_get_name(&self, category: &str, idx: usize) -> String { sys::marker_get_name(self.r(), category, idx) }
    pub fn marker_get_category(&self, category: &str, idx: usize) -> String { sys::marker_get_category(self.r(), category, idx) }
    pub fn marker_get_tech_layer(&self, category: &str, idx: usize) -> String { sys::marker_get_tech_layer(self.r(), category, idx) }
    pub fn marker_get_b_box_x_min(&self, category: &str, idx: usize) -> i32 { sys::marker_get_b_box_x_min(self.r(), category, idx) }
    pub fn marker_get_b_box_y_min(&self, category: &str, idx: usize) -> i32 { sys::marker_get_b_box_y_min(self.r(), category, idx) }
    pub fn marker_get_b_box_x_max(&self, category: &str, idx: usize) -> i32 { sys::marker_get_b_box_x_max(self.r(), category, idx) }
    pub fn marker_get_b_box_y_max(&self, category: &str, idx: usize) -> i32 { sys::marker_get_b_box_y_max(self.r(), category, idx) }
    pub fn marker_get_b_box_dx(&self, category: &str, idx: usize) -> i32 { sys::marker_get_b_box_dx(self.r(), category, idx) }
    pub fn marker_get_b_box_dy(&self, category: &str, idx: usize) -> i32 { sys::marker_get_b_box_dy(self.r(), category, idx) }
    pub fn modinst_get_name(&self, path: &str) -> String { sys::modinst_get_name(self.r(), path) }
    pub fn modinst_get_parent(&self, path: &str) -> String { sys::modinst_get_parent(self.r(), path) }
    pub fn modinst_get_master(&self, path: &str) -> String { sys::modinst_get_master(self.r(), path) }
    pub fn modinst_get_group(&self, path: &str) -> String { sys::modinst_get_group(self.r(), path) }
    pub fn modinst_get_hierarchical_name(&self, path: &str) -> String { sys::modinst_get_hierarchical_name(self.r(), path) }
    pub fn modinst_get_mod_i_terms(&self, path: &str) -> Vec<String> { (0..sys::num_modinst_get_mod_i_terms(self.r(), path)).map(|i| sys::nth_modinst_get_mod_i_terms(self.r(), path, i)).collect() }
    pub fn modnet_get_parent(&self, name: &str) -> String { sys::modnet_get_parent(self.r(), name) }
    pub fn modnet_get_mod_i_terms(&self, name: &str) -> Vec<String> { (0..sys::num_modnet_get_mod_i_terms(self.r(), name)).map(|i| sys::nth_modnet_get_mod_i_terms(self.r(), name, i)).collect() }
    pub fn modnet_get_mod_b_terms(&self, name: &str) -> Vec<String> { (0..sys::num_modnet_get_mod_b_terms(self.r(), name)).map(|i| sys::nth_modnet_get_mod_b_terms(self.r(), name, i)).collect() }
    pub fn modnet_get_i_terms(&self, name: &str) -> Vec<String> { (0..sys::num_modnet_get_i_terms(self.r(), name)).map(|i| sys::nth_modnet_get_i_terms(self.r(), name, i)).collect() }
    pub fn modnet_get_b_terms(&self, name: &str) -> Vec<String> { (0..sys::num_modnet_get_b_terms(self.r(), name)).map(|i| sys::nth_modnet_get_b_terms(self.r(), name, i)).collect() }
    pub fn modnet_get_name(&self, name: &str) -> String { sys::modnet_get_name(self.r(), name) }
    pub fn modnet_get_const_name(&self, name: &str) -> String { sys::modnet_get_const_name(self.r(), name) }
    pub fn modnet_get_hierarchical_name(&self, name: &str) -> String { sys::modnet_get_hierarchical_name(self.r(), name) }
    pub fn modnet_find_related_net(&self, name: &str) -> String { sys::modnet_find_related_net(self.r(), name) }
    pub fn modnet_get_next_mod_nets_in_fanin(&self, name: &str) -> Vec<String> { (0..sys::num_modnet_get_next_mod_nets_in_fanin(self.r(), name)).map(|i| sys::nth_modnet_get_next_mod_nets_in_fanin(self.r(), name, i)).collect() }
    pub fn modnet_get_next_mod_nets_in_fanout(&self, name: &str) -> Vec<String> { (0..sys::num_modnet_get_next_mod_nets_in_fanout(self.r(), name)).map(|i| sys::nth_modnet_get_next_mod_nets_in_fanout(self.r(), name, i)).collect() }
    pub fn modnet_get_first_parent_mod_net(&self, name: &str) -> String { sys::modnet_get_first_parent_mod_net(self.r(), name) }
    pub fn modbterm_get_name(&self, module: &str, idx: usize) -> String { sys::modbterm_get_name(self.r(), module, idx) }
    pub fn modbterm_get_parent(&self, module: &str, idx: usize) -> String { sys::modbterm_get_parent(self.r(), module, idx) }
    pub fn modbterm_get_hierarchical_name(&self, module: &str, idx: usize) -> String { sys::modbterm_get_hierarchical_name(self.r(), module, idx) }
    pub fn modbterm_get_parent_mod_i_term(&self, module: &str, idx: usize) -> String { sys::modbterm_get_parent_mod_i_term(self.r(), module, idx) }
    pub fn modbterm_get_mod_net(&self, module: &str, idx: usize) -> String { sys::modbterm_get_mod_net(self.r(), module, idx) }
    pub fn modbterm_get_sig_type(&self, module: &str, idx: usize) -> String { sys::modbterm_get_sig_type(self.r(), module, idx) }
    pub fn modbterm_get_io_type(&self, module: &str, idx: usize) -> String { sys::modbterm_get_io_type(self.r(), module, idx) }
    pub fn modbterm_is_bus_port(&self, module: &str, idx: usize) -> bool { sys::modbterm_is_bus_port(self.r(), module, idx) }
    pub fn modbterm_get_mod_inst(&self, module: &str, idx: usize) -> String { sys::modbterm_get_mod_inst(self.r(), module, idx) }
    pub fn moditerm_get_name(&self, modinst: &str, idx: usize) -> String { sys::moditerm_get_name(self.r(), modinst, idx) }
    pub fn moditerm_get_parent(&self, modinst: &str, idx: usize) -> String { sys::moditerm_get_parent(self.r(), modinst, idx) }
    pub fn moditerm_get_hierarchical_name(&self, modinst: &str, idx: usize) -> String { sys::moditerm_get_hierarchical_name(self.r(), modinst, idx) }
    pub fn moditerm_get_mod_net(&self, modinst: &str, idx: usize) -> String { sys::moditerm_get_mod_net(self.r(), modinst, idx) }
    pub fn moditerm_get_child_mod_b_term(&self, modinst: &str, idx: usize) -> String { sys::moditerm_get_child_mod_b_term(self.r(), modinst, idx) }
}
