// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/generate-bindings.py from docs/derived-core-schema.json -- DO NOT EDIT.
// Machine-generated `Db` SETTERS (L2/write). include!()'d into lib.rs behind `gen-write`.
// &mut self + Result<()>; throws (-> Err) when the addressed object does not exist.

impl Db {
    pub fn block_clear_global_connect(&mut self) -> crate::Result<()> { Ok(sys::block_clear_global_connect(self.r())?) }
    pub fn block_set_corner_name_list(&mut self, name_list: &str) -> crate::Result<()> { Ok(sys::block_set_corner_name_list(self.r(), name_list)?) }
    pub fn block_set_corner_count(&mut self, corner_cnt: i32, ext_db_cnt: i32, name_list: &str) -> crate::Result<()> { Ok(sys::block_set_corner_count(self.r(), corner_cnt, ext_db_cnt, name_list)?) }
    pub fn block_set_min_routing_layer(&mut self, min_routing_layer: i32) -> crate::Result<()> { Ok(sys::block_set_min_routing_layer(self.r(), min_routing_layer)?) }
    pub fn block_set_max_routing_layer(&mut self, max_routing_layer: i32) -> crate::Result<()> { Ok(sys::block_set_max_routing_layer(self.r(), max_routing_layer)?) }
    pub fn block_set_min_layer_for_clock(&mut self, min_layer_for_clock: i32) -> crate::Result<()> { Ok(sys::block_set_min_layer_for_clock(self.r(), min_layer_for_clock)?) }
    pub fn block_set_max_layer_for_clock(&mut self, max_layer_for_clock: i32) -> crate::Result<()> { Ok(sys::block_set_max_layer_for_clock(self.r(), max_layer_for_clock)?) }
    pub fn block_clear(&mut self) -> crate::Result<()> { Ok(sys::block_clear(self.r())?) }
    pub fn block_set_driving_itermsfor_nets(&mut self) -> crate::Result<()> { Ok(sys::block_set_driving_itermsfor_nets(self.r())?) }
    pub fn block_clear_user_inst_flags(&mut self) -> crate::Result<()> { Ok(sys::block_clear_user_inst_flags(self.r())?) }
    pub fn inst_set_origin(&mut self, inst: &str, x: i32, y: i32) -> crate::Result<()> { Ok(sys::inst_set_origin(self.r(), inst, x, y)?) }
    pub fn inst_set_orient(&mut self, inst: &str, orient: &str) -> crate::Result<()> { Ok(sys::inst_set_orient(self.r(), inst, orient)?) }
    pub fn inst_set_location(&mut self, inst: &str, x: i32, y: i32) -> crate::Result<()> { Ok(sys::inst_set_location(self.r(), inst, x, y)?) }
    pub fn inst_set_location_orient(&mut self, inst: &str, orient: &str) -> crate::Result<()> { Ok(sys::inst_set_location_orient(self.r(), inst, orient)?) }
    pub fn inst_set_placement_status(&mut self, inst: &str, status: &str) -> crate::Result<()> { Ok(sys::inst_set_placement_status(self.r(), inst, status)?) }
    pub fn inst_set_eco_create(&mut self, inst: &str, v: bool) -> crate::Result<()> { Ok(sys::inst_set_eco_create(self.r(), inst, v)?) }
    pub fn inst_set_eco_destroy(&mut self, inst: &str, v: bool) -> crate::Result<()> { Ok(sys::inst_set_eco_destroy(self.r(), inst, v)?) }
    pub fn inst_set_eco_modify(&mut self, inst: &str, v: bool) -> crate::Result<()> { Ok(sys::inst_set_eco_modify(self.r(), inst, v)?) }
    pub fn inst_set_user_flag1(&mut self, inst: &str) -> crate::Result<()> { Ok(sys::inst_set_user_flag1(self.r(), inst)?) }
    pub fn inst_clear_user_flag1(&mut self, inst: &str) -> crate::Result<()> { Ok(sys::inst_clear_user_flag1(self.r(), inst)?) }
    pub fn inst_set_user_flag2(&mut self, inst: &str) -> crate::Result<()> { Ok(sys::inst_set_user_flag2(self.r(), inst)?) }
    pub fn inst_clear_user_flag2(&mut self, inst: &str) -> crate::Result<()> { Ok(sys::inst_clear_user_flag2(self.r(), inst)?) }
    pub fn inst_set_user_flag3(&mut self, inst: &str) -> crate::Result<()> { Ok(sys::inst_set_user_flag3(self.r(), inst)?) }
    pub fn inst_clear_user_flag3(&mut self, inst: &str) -> crate::Result<()> { Ok(sys::inst_clear_user_flag3(self.r(), inst)?) }
    pub fn inst_set_do_not_touch(&mut self, inst: &str, v: bool) -> crate::Result<()> { Ok(sys::inst_set_do_not_touch(self.r(), inst, v)?) }
    pub fn inst_set_halo(&mut self, inst: &str, left: i32, bottom: i32, right: i32, top: i32, is_soft: bool) -> crate::Result<()> { Ok(sys::inst_set_halo(self.r(), inst, left, bottom, right, top, is_soft)?) }
    pub fn inst_set_weight(&mut self, inst: &str, weight: i32) -> crate::Result<()> { Ok(sys::inst_set_weight(self.r(), inst, weight)?) }
    pub fn inst_set_source_type(&mut self, inst: &str, a0: &str) -> crate::Result<()> { Ok(sys::inst_set_source_type(self.r(), inst, a0)?) }
    pub fn inst_set_pin_access_idx(&mut self, inst: &str, idx: u32) -> crate::Result<()> { Ok(sys::inst_set_pin_access_idx(self.r(), inst, idx)?) }
    pub fn net_set_r_c_disconnected(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_r_c_disconnected(self.r(), net, value)?) }
    pub fn net_set_weight(&mut self, net: &str, weight: i32) -> crate::Result<()> { Ok(sys::net_set_weight(self.r(), net, weight)?) }
    pub fn net_set_source_type(&mut self, net: &str, a0: &str) -> crate::Result<()> { Ok(sys::net_set_source_type(self.r(), net, a0)?) }
    pub fn net_set_x_talk_class(&mut self, net: &str, value: i32) -> crate::Result<()> { Ok(sys::net_set_x_talk_class(self.r(), net, value)?) }
    pub fn net_set_fixed_bump(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_fixed_bump(self.r(), net, value)?) }
    pub fn net_set_wire_type(&mut self, net: &str, wire_type: &str) -> crate::Result<()> { Ok(sys::net_set_wire_type(self.r(), net, wire_type)?) }
    pub fn net_set_sig_type(&mut self, net: &str, sig_type: &str) -> crate::Result<()> { Ok(sys::net_set_sig_type(self.r(), net, sig_type)?) }
    pub fn net_set_mark(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_mark(self.r(), net, value)?) }
    pub fn net_set_mark_1(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_mark_1(self.r(), net, value)?) }
    pub fn net_set_select(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_select(self.r(), net, value)?) }
    pub fn net_set_wire_ordered(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_wire_ordered(self.r(), net, value)?) }
    pub fn net_set_disconnected(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_disconnected(self.r(), net, value)?) }
    pub fn net_set_wire_altered(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_wire_altered(self.r(), net, value)?) }
    pub fn net_set_r_cgraph(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_r_cgraph(self.r(), net, value)?) }
    pub fn net_set_extracted(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_extracted(self.r(), net, value)?) }
    pub fn net_set_spef(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_spef(self.r(), net, value)?) }
    pub fn net_set_do_not_touch(&mut self, net: &str, v: bool) -> crate::Result<()> { Ok(sys::net_set_do_not_touch(self.r(), net, v)?) }
    pub fn net_set_special(&mut self, net: &str) -> crate::Result<()> { Ok(sys::net_set_special(self.r(), net)?) }
    pub fn net_clear_special(&mut self, net: &str) -> crate::Result<()> { Ok(sys::net_clear_special(self.r(), net)?) }
    pub fn net_set_i_oflag(&mut self, net: &str) -> crate::Result<()> { Ok(sys::net_set_i_oflag(self.r(), net)?) }
    pub fn net_set_wild_connected(&mut self, net: &str) -> crate::Result<()> { Ok(sys::net_set_wild_connected(self.r(), net)?) }
    pub fn net_clear_wild_connected(&mut self, net: &str) -> crate::Result<()> { Ok(sys::net_clear_wild_connected(self.r(), net)?) }
    pub fn net_set_gndc_calib_factor(&mut self, net: &str, gndc_calib: f32) -> crate::Result<()> { Ok(sys::net_set_gndc_calib_factor(self.r(), net, gndc_calib)?) }
    pub fn net_set_cc_calib_factor(&mut self, net: &str, cc_calib: f32) -> crate::Result<()> { Ok(sys::net_set_cc_calib_factor(self.r(), net, cc_calib)?) }
    pub fn net_set_cc_adjust_factor(&mut self, net: &str, factor: f32) -> crate::Result<()> { Ok(sys::net_set_cc_adjust_factor(self.r(), net, factor)?) }
    pub fn net_set_cc_adjust_order(&mut self, net: &str, order: u32) -> crate::Result<()> { Ok(sys::net_set_cc_adjust_order(self.r(), net, order)?) }
    pub fn net_set_db_cc(&mut self, net: &str, cap: f32) -> crate::Result<()> { Ok(sys::net_set_db_cc(self.r(), net, cap)?) }
    pub fn net_set_ref_cc(&mut self, net: &str, cap: f32) -> crate::Result<()> { Ok(sys::net_set_ref_cc(self.r(), net, cap)?) }
    pub fn net_set_cc_match_ratio(&mut self, net: &str, ratio: f32) -> crate::Result<()> { Ok(sys::net_set_cc_match_ratio(self.r(), net, ratio)?) }
    pub fn net_set1st_r_seg_id(&mut self, net: &str, rseg_id: u32) -> crate::Result<()> { Ok(sys::net_set1st_r_seg_id(self.r(), net, rseg_id)?) }
    pub fn net_set1st_cap_node_id(&mut self, net: &str, capn_id: u32) -> crate::Result<()> { Ok(sys::net_set1st_cap_node_id(self.r(), net, capn_id)?) }
    pub fn net_set_term_ext_ids(&mut self, net: &str, cap_id: i32) -> crate::Result<()> { Ok(sys::net_set_term_ext_ids(self.r(), net, cap_id)?) }
    pub fn net_clear_guides(&mut self, net: &str) -> crate::Result<()> { Ok(sys::net_clear_guides(self.r(), net)?) }
    pub fn net_clear_tracks(&mut self, net: &str) -> crate::Result<()> { Ok(sys::net_clear_tracks(self.r(), net)?) }
    pub fn net_set_jumpers(&mut self, net: &str, has_jumpers: bool) -> crate::Result<()> { Ok(sys::net_set_jumpers(self.r(), net, has_jumpers)?) }
    pub fn net_set_auto_taper(&mut self, net: &str, enable: bool) -> crate::Result<()> { Ok(sys::net_set_auto_taper(self.r(), net, enable)?) }
    pub fn bterm_set_sig_type(&mut self, bterm: &str, a0: &str) -> crate::Result<()> { Ok(sys::bterm_set_sig_type(self.r(), bterm, a0)?) }
    pub fn bterm_set_spef_mark(&mut self, bterm: &str, v: u32) -> crate::Result<()> { Ok(sys::bterm_set_spef_mark(self.r(), bterm, v)?) }
    pub fn bterm_set_mark(&mut self, bterm: &str, v: u32) -> crate::Result<()> { Ok(sys::bterm_set_mark(self.r(), bterm, v)?) }
    pub fn bterm_set_ext_id(&mut self, bterm: &str, v: u32) -> crate::Result<()> { Ok(sys::bterm_set_ext_id(self.r(), bterm, v)?) }
    pub fn bterm_set_special(&mut self, bterm: &str) -> crate::Result<()> { Ok(sys::bterm_set_special(self.r(), bterm)?) }
    pub fn master_set_origin(&mut self, master: &str, x: i32, y: i32) -> crate::Result<()> { Ok(sys::master_set_origin(self.r(), master, x, y)?) }
    pub fn master_set_width(&mut self, master: &str, width: u32) -> crate::Result<()> { Ok(sys::master_set_width(self.r(), master, width)?) }
    pub fn master_set_height(&mut self, master: &str, height: u32) -> crate::Result<()> { Ok(sys::master_set_height(self.r(), master, height)?) }
    pub fn master_set_backside_bridge(&mut self, master: &str, is_bridge: bool) -> crate::Result<()> { Ok(sys::master_set_backside_bridge(self.r(), master, is_bridge)?) }
    pub fn master_set_symmetry_x(&mut self, master: &str) -> crate::Result<()> { Ok(sys::master_set_symmetry_x(self.r(), master)?) }
    pub fn master_set_symmetry_y(&mut self, master: &str) -> crate::Result<()> { Ok(sys::master_set_symmetry_y(self.r(), master)?) }
    pub fn master_set_symmetry_r90(&mut self, master: &str) -> crate::Result<()> { Ok(sys::master_set_symmetry_r90(self.r(), master)?) }
    pub fn master_set_frozen(&mut self, master: &str) -> crate::Result<()> { Ok(sys::master_set_frozen(self.r(), master)?) }
    pub fn master_set_sequential(&mut self, master: &str, v: bool) -> crate::Result<()> { Ok(sys::master_set_sequential(self.r(), master, v)?) }
    pub fn master_set_mark(&mut self, master: &str, mark: u32) -> crate::Result<()> { Ok(sys::master_set_mark(self.r(), master, mark)?) }
    pub fn master_set_special_power(&mut self, master: &str, v: bool) -> crate::Result<()> { Ok(sys::master_set_special_power(self.r(), master, v)?) }
    pub fn master_clear_pin_access(&mut self, master: &str, pin_access_idx: i32) -> crate::Result<()> { Ok(sys::master_clear_pin_access(self.r(), master, pin_access_idx)?) }
    pub fn iterm_set_spef(&mut self, inst: &str, pin: &str, v: u32) -> crate::Result<()> { Ok(sys::iterm_set_spef(self.r(), inst, pin, v)?) }
    pub fn iterm_set_ext_id(&mut self, inst: &str, pin: &str, v: u32) -> crate::Result<()> { Ok(sys::iterm_set_ext_id(self.r(), inst, pin, v)?) }
    pub fn iterm_set_special(&mut self, inst: &str, pin: &str) -> crate::Result<()> { Ok(sys::iterm_set_special(self.r(), inst, pin)?) }
    pub fn iterm_clear_special(&mut self, inst: &str, pin: &str) -> crate::Result<()> { Ok(sys::iterm_clear_special(self.r(), inst, pin)?) }
    pub fn iterm_set_clocked(&mut self, inst: &str, pin: &str, v: bool) -> crate::Result<()> { Ok(sys::iterm_set_clocked(self.r(), inst, pin, v)?) }
    pub fn iterm_set_mark(&mut self, inst: &str, pin: &str, v: u32) -> crate::Result<()> { Ok(sys::iterm_set_mark(self.r(), inst, pin, v)?) }
    pub fn iterm_set_connected(&mut self, inst: &str, pin: &str) -> crate::Result<()> { Ok(sys::iterm_set_connected(self.r(), inst, pin)?) }
    pub fn iterm_clear_connected(&mut self, inst: &str, pin: &str) -> crate::Result<()> { Ok(sys::iterm_clear_connected(self.r(), inst, pin)?) }
    pub fn iterm_clear_pref_access_points(&mut self, inst: &str, pin: &str) -> crate::Result<()> { Ok(sys::iterm_clear_pref_access_points(self.r(), inst, pin)?) }
    pub fn mterm_set_sig_type(&mut self, master: &str, term: &str, a0: &str) -> crate::Result<()> { Ok(sys::mterm_set_sig_type(self.r(), master, term, a0)?) }
    pub fn mterm_set_mark(&mut self, master: &str, term: &str, v: u32) -> crate::Result<()> { Ok(sys::mterm_set_mark(self.r(), master, term, v)?) }
    pub fn layer_set_wrong_way_width(&mut self, layer: &str, wrong_way_width: u32) -> crate::Result<()> { Ok(sys::layer_set_wrong_way_width(self.r(), layer, wrong_way_width)?) }
    pub fn layer_set_wrong_way_min_width(&mut self, layer: &str, wrong_way_min_width: u32) -> crate::Result<()> { Ok(sys::layer_set_wrong_way_min_width(self.r(), layer, wrong_way_min_width)?) }
    pub fn layer_set_layer_adjustment(&mut self, layer: &str, layer_adjustment: f32) -> crate::Result<()> { Ok(sys::layer_set_layer_adjustment(self.r(), layer, layer_adjustment)?) }
    pub fn layer_set_rect_only(&mut self, layer: &str, rect_only: bool) -> crate::Result<()> { Ok(sys::layer_set_rect_only(self.r(), layer, rect_only)?) }
    pub fn layer_set_right_way_on_grid_only(&mut self, layer: &str, right_way_on_grid_only: bool) -> crate::Result<()> { Ok(sys::layer_set_right_way_on_grid_only(self.r(), layer, right_way_on_grid_only)?) }
    pub fn layer_set_right_way_on_grid_only_check_mask(&mut self, layer: &str, right_way_on_grid_only_check_mask: bool) -> crate::Result<()> { Ok(sys::layer_set_right_way_on_grid_only_check_mask(self.r(), layer, right_way_on_grid_only_check_mask)?) }
    pub fn layer_set_rect_only_except_non_core_pins(&mut self, layer: &str, rect_only_except_non_core_pins: bool) -> crate::Result<()> { Ok(sys::layer_set_rect_only_except_non_core_pins(self.r(), layer, rect_only_except_non_core_pins)?) }
    pub fn layer_set_backside(&mut self, layer: &str, is_backside: bool) -> crate::Result<()> { Ok(sys::layer_set_backside(self.r(), layer, is_backside)?) }
    pub fn layer_set_alias(&mut self, layer: &str, alias: &str) -> crate::Result<()> { Ok(sys::layer_set_alias(self.r(), layer, alias)?) }
    pub fn layer_set_width(&mut self, layer: &str, width: i32) -> crate::Result<()> { Ok(sys::layer_set_width(self.r(), layer, width)?) }
    pub fn layer_set_spacing(&mut self, layer: &str, spacing: i32) -> crate::Result<()> { Ok(sys::layer_set_spacing(self.r(), layer, spacing)?) }
    pub fn layer_set_num_masks(&mut self, layer: &str, number: u32) -> crate::Result<()> { Ok(sys::layer_set_num_masks(self.r(), layer, number)?) }
    pub fn layer_set_pitch(&mut self, layer: &str, pitch: i32) -> crate::Result<()> { Ok(sys::layer_set_pitch(self.r(), layer, pitch)?) }
    pub fn layer_set_pitch_x_y(&mut self, layer: &str, pitch_x: i32, pitch_y: i32) -> crate::Result<()> { Ok(sys::layer_set_pitch_x_y(self.r(), layer, pitch_x, pitch_y)?) }
    pub fn layer_set_first_last_pitch(&mut self, layer: &str, first_last_pitch: i32) -> crate::Result<()> { Ok(sys::layer_set_first_last_pitch(self.r(), layer, first_last_pitch)?) }
    pub fn layer_set_offset(&mut self, layer: &str, pitch: i32) -> crate::Result<()> { Ok(sys::layer_set_offset(self.r(), layer, pitch)?) }
    pub fn layer_set_offset_x_y(&mut self, layer: &str, pitch_x: i32, pitch_y: i32) -> crate::Result<()> { Ok(sys::layer_set_offset_x_y(self.r(), layer, pitch_x, pitch_y)?) }
    pub fn layer_set_thickness(&mut self, layer: &str, thickness: u32) -> crate::Result<()> { Ok(sys::layer_set_thickness(self.r(), layer, thickness)?) }
    pub fn layer_set_area(&mut self, layer: &str, area: i64) -> crate::Result<()> { Ok(sys::layer_set_area(self.r(), layer, area)?) }
    pub fn layer_set_max_width(&mut self, layer: &str, max_width: u32) -> crate::Result<()> { Ok(sys::layer_set_max_width(self.r(), layer, max_width)?) }
    pub fn layer_set_min_width(&mut self, layer: &str, max_width: u32) -> crate::Result<()> { Ok(sys::layer_set_min_width(self.r(), layer, max_width)?) }
    pub fn layer_set_min_step(&mut self, layer: &str, min_step: u32) -> crate::Result<()> { Ok(sys::layer_set_min_step(self.r(), layer, min_step)?) }
    pub fn layer_set_min_step_max_length(&mut self, layer: &str, length: u32) -> crate::Result<()> { Ok(sys::layer_set_min_step_max_length(self.r(), layer, length)?) }
    pub fn layer_set_min_step_max_edges(&mut self, layer: &str, edges: u32) -> crate::Result<()> { Ok(sys::layer_set_min_step_max_edges(self.r(), layer, edges)?) }
    pub fn layer_set_resistance(&mut self, layer: &str, res: f64) -> crate::Result<()> { Ok(sys::layer_set_resistance(self.r(), layer, res)?) }
    pub fn layer_set_capacitance(&mut self, layer: &str, cap: f64) -> crate::Result<()> { Ok(sys::layer_set_capacitance(self.r(), layer, cap)?) }
    pub fn layer_set_edge_capacitance(&mut self, layer: &str, cap: f64) -> crate::Result<()> { Ok(sys::layer_set_edge_capacitance(self.r(), layer, cap)?) }
    pub fn layer_set_wire_extension(&mut self, layer: &str, ext: u32) -> crate::Result<()> { Ok(sys::layer_set_wire_extension(self.r(), layer, ext)?) }
    pub fn via_set_pattern(&mut self, via: &str, pattern: &str) -> crate::Result<()> { Ok(sys::via_set_pattern(self.r(), via, pattern)?) }
    pub fn techvia_set_default(&mut self, via: &str) -> crate::Result<()> { Ok(sys::techvia_set_default(self.r(), via)?) }
    pub fn techvia_set_top_of_stack(&mut self, via: &str) -> crate::Result<()> { Ok(sys::techvia_set_top_of_stack(self.r(), via)?) }
    pub fn techvia_set_resistance(&mut self, via: &str, res: f64) -> crate::Result<()> { Ok(sys::techvia_set_resistance(self.r(), via, res)?) }
    pub fn techvia_set_pattern(&mut self, via: &str, pattern: &str) -> crate::Result<()> { Ok(sys::techvia_set_pattern(self.r(), via, pattern)?) }
    pub fn ndr_set_hard_spacing(&mut self, rule: &str, value: bool) -> crate::Result<()> { Ok(sys::ndr_set_hard_spacing(self.r(), rule, value)?) }
    pub fn site_set_width(&mut self, site: &str, width: i32) -> crate::Result<()> { Ok(sys::site_set_width(self.r(), site, width)?) }
    pub fn site_set_height(&mut self, site: &str, height: i32) -> crate::Result<()> { Ok(sys::site_set_height(self.r(), site, height)?) }
    pub fn site_set_symmetry_x(&mut self, site: &str) -> crate::Result<()> { Ok(sys::site_set_symmetry_x(self.r(), site)?) }
    pub fn site_set_symmetry_y(&mut self, site: &str) -> crate::Result<()> { Ok(sys::site_set_symmetry_y(self.r(), site)?) }
    pub fn site_set_symmetry_r90(&mut self, site: &str) -> crate::Result<()> { Ok(sys::site_set_symmetry_r90(self.r(), site)?) }
    pub fn obs_set_slot_obstruction(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::obs_set_slot_obstruction(self.r(), idx)?) }
    pub fn obs_set_fill_obstruction(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::obs_set_fill_obstruction(self.r(), idx)?) }
    pub fn obs_set_except_p_g_nets_obstruction(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::obs_set_except_p_g_nets_obstruction(self.r(), idx)?) }
    pub fn obs_set_pushed_down(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::obs_set_pushed_down(self.r(), idx)?) }
    pub fn obs_set_effective_width(&mut self, idx: usize, w: i32) -> crate::Result<()> { Ok(sys::obs_set_effective_width(self.r(), idx, w)?) }
    pub fn obs_set_min_spacing(&mut self, idx: usize, w: i32) -> crate::Result<()> { Ok(sys::obs_set_min_spacing(self.r(), idx, w)?) }
    pub fn obs_set_is_system_reserved(&mut self, idx: usize, is_system_reserved: bool) -> crate::Result<()> { Ok(sys::obs_set_is_system_reserved(self.r(), idx, is_system_reserved)?) }
    pub fn swire_set_wire_type(&mut self, net: &str, idx: usize, a0: &str) -> crate::Result<()> { Ok(sys::swire_set_wire_type(self.r(), net, idx, a0)?) }
    pub fn wire_set_property(&mut self, net: &str, jid: i32, property: i32) -> crate::Result<()> { Ok(sys::wire_set_property(self.r(), net, jid, property)?) }
    pub fn box_set_soft(&mut self, idx: usize, value: bool) -> crate::Result<()> { Ok(sys::box_set_soft(self.r(), idx, value)?) }
    pub fn box_set_layer_mask(&mut self, idx: usize, mask: u32) -> crate::Result<()> { Ok(sys::box_set_layer_mask(self.r(), idx, mask)?) }
    pub fn region_set_invalid(&mut self, region: &str, v: bool) -> crate::Result<()> { Ok(sys::region_set_invalid(self.r(), region, v)?) }
    pub fn blockage_set_pushed_down(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::blockage_set_pushed_down(self.r(), idx)?) }
    pub fn blockage_set_soft(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::blockage_set_soft(self.r(), idx)?) }
    pub fn blockage_set_is_system_reserved(&mut self, idx: usize, is_system_reserved: bool) -> crate::Result<()> { Ok(sys::blockage_set_is_system_reserved(self.r(), idx, is_system_reserved)?) }
    pub fn blockage_set_max_density(&mut self, idx: usize, max_density: f32) -> crate::Result<()> { Ok(sys::blockage_set_max_density(self.r(), idx, max_density)?) }
    pub fn marker_cat_set_description(&mut self, category: &str, description: &str) -> crate::Result<()> { Ok(sys::marker_cat_set_description(self.r(), category, description)?) }
    pub fn marker_cat_set_source(&mut self, category: &str, source: &str) -> crate::Result<()> { Ok(sys::marker_cat_set_source(self.r(), category, source)?) }
    pub fn marker_cat_set_max_markers(&mut self, category: &str, max_markers: i32) -> crate::Result<()> { Ok(sys::marker_cat_set_max_markers(self.r(), category, max_markers)?) }
    pub fn marker_set_comment(&mut self, category: &str, idx: usize, comment: &str) -> crate::Result<()> { Ok(sys::marker_set_comment(self.r(), category, idx, comment)?) }
    pub fn marker_set_line_number(&mut self, category: &str, idx: usize, line_number: i32) -> crate::Result<()> { Ok(sys::marker_set_line_number(self.r(), category, idx, line_number)?) }
    pub fn marker_set_visited(&mut self, category: &str, idx: usize, visited: bool) -> crate::Result<()> { Ok(sys::marker_set_visited(self.r(), category, idx, visited)?) }
    pub fn marker_set_visible(&mut self, category: &str, idx: usize, visible: bool) -> crate::Result<()> { Ok(sys::marker_set_visible(self.r(), category, idx, visible)?) }
    pub fn marker_set_waived(&mut self, category: &str, idx: usize, waived: bool) -> crate::Result<()> { Ok(sys::marker_set_waived(self.r(), category, idx, waived)?) }
    pub fn pwr_domain_set_top(&mut self, name: &str, top: bool) -> crate::Result<()> { Ok(sys::pwr_domain_set_top(self.r(), name, top)?) }
    pub fn pwr_domain_set_voltage(&mut self, name: &str, voltage: f32) -> crate::Result<()> { Ok(sys::pwr_domain_set_voltage(self.r(), name, voltage)?) }
    pub fn pwr_switch_set_out_supply_port(&mut self, name: &str, out_port: &str, net: &str) -> crate::Result<()> { Ok(sys::pwr_switch_set_out_supply_port(self.r(), name, out_port, net)?) }
    pub fn isolation_set_applies_to(&mut self, name: &str, applies_to: &str) -> crate::Result<()> { Ok(sys::isolation_set_applies_to(self.r(), name, applies_to)?) }
    pub fn isolation_set_clamp_value(&mut self, name: &str, clamp_value: &str) -> crate::Result<()> { Ok(sys::isolation_set_clamp_value(self.r(), name, clamp_value)?) }
    pub fn isolation_set_isolation_signal(&mut self, name: &str, isolation_signal: &str) -> crate::Result<()> { Ok(sys::isolation_set_isolation_signal(self.r(), name, isolation_signal)?) }
    pub fn isolation_set_isolation_sense(&mut self, name: &str, isolation_sense: &str) -> crate::Result<()> { Ok(sys::isolation_set_isolation_sense(self.r(), name, isolation_sense)?) }
    pub fn isolation_set_location(&mut self, name: &str, location: &str) -> crate::Result<()> { Ok(sys::isolation_set_location(self.r(), name, location)?) }
    pub fn level_shifter_set_source(&mut self, name: &str, source: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_source(self.r(), name, source)?) }
    pub fn level_shifter_set_sink(&mut self, name: &str, sink: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_sink(self.r(), name, sink)?) }
    pub fn level_shifter_set_use_functional_equivalence(&mut self, name: &str, use_functional_equivalence: bool) -> crate::Result<()> { Ok(sys::level_shifter_set_use_functional_equivalence(self.r(), name, use_functional_equivalence)?) }
    pub fn level_shifter_set_applies_to(&mut self, name: &str, applies_to: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_applies_to(self.r(), name, applies_to)?) }
    pub fn level_shifter_set_applies_to_boundary(&mut self, name: &str, applies_to_boundary: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_applies_to_boundary(self.r(), name, applies_to_boundary)?) }
    pub fn level_shifter_set_rule(&mut self, name: &str, rule: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_rule(self.r(), name, rule)?) }
    pub fn level_shifter_set_threshold(&mut self, name: &str, threshold: f32) -> crate::Result<()> { Ok(sys::level_shifter_set_threshold(self.r(), name, threshold)?) }
    pub fn level_shifter_set_no_shift(&mut self, name: &str, no_shift: bool) -> crate::Result<()> { Ok(sys::level_shifter_set_no_shift(self.r(), name, no_shift)?) }
    pub fn level_shifter_set_force_shift(&mut self, name: &str, force_shift: bool) -> crate::Result<()> { Ok(sys::level_shifter_set_force_shift(self.r(), name, force_shift)?) }
    pub fn level_shifter_set_location(&mut self, name: &str, location: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_location(self.r(), name, location)?) }
    pub fn level_shifter_set_input_supply(&mut self, name: &str, input_supply: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_input_supply(self.r(), name, input_supply)?) }
    pub fn level_shifter_set_output_supply(&mut self, name: &str, output_supply: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_output_supply(self.r(), name, output_supply)?) }
    pub fn level_shifter_set_internal_supply(&mut self, name: &str, internal_supply: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_internal_supply(self.r(), name, internal_supply)?) }
    pub fn level_shifter_set_name_prefix(&mut self, name: &str, name_prefix: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_name_prefix(self.r(), name, name_prefix)?) }
    pub fn level_shifter_set_name_suffix(&mut self, name: &str, name_suffix: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_name_suffix(self.r(), name, name_suffix)?) }
    pub fn level_shifter_set_cell_name(&mut self, name: &str, cell_name: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_cell_name(self.r(), name, cell_name)?) }
    pub fn level_shifter_set_cell_input(&mut self, name: &str, cell_input: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_cell_input(self.r(), name, cell_input)?) }
    pub fn level_shifter_set_cell_output(&mut self, name: &str, cell_output: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_cell_output(self.r(), name, cell_output)?) }
    pub fn tech_set_lef_units(&mut self, units: i32) -> crate::Result<()> { Ok(sys::tech_set_lef_units(self.r(), units)?) }
    pub fn tech_set_lef_version(&mut self, inver: f64) -> crate::Result<()> { Ok(sys::tech_set_lef_version(self.r(), inver)?) }
    pub fn tech_set_manufacturing_grid(&mut self, ingrd: i32) -> crate::Result<()> { Ok(sys::tech_set_manufacturing_grid(self.r(), ingrd)?) }
    pub fn lib_set_lef_units(&mut self, name: &str, units: i32) -> crate::Result<()> { Ok(sys::lib_set_lef_units(self.r(), name, units)?) }
    pub fn capnode_set_capacitance(&mut self, idx: usize, cap: f64, corner: i32) -> crate::Result<()> { Ok(sys::capnode_set_capacitance(self.r(), idx, cap, corner)?) }
    pub fn capnode_set_node(&mut self, idx: usize, nodeid: u32) -> crate::Result<()> { Ok(sys::capnode_set_node(self.r(), idx, nodeid)?) }
    pub fn capnode_set_select(&mut self, idx: usize, value: bool) -> crate::Result<()> { Ok(sys::capnode_set_select(self.r(), idx, value)?) }
    pub fn capnode_set_children_cnt(&mut self, idx: usize, cnt: u32) -> crate::Result<()> { Ok(sys::capnode_set_children_cnt(self.r(), idx, cnt)?) }
    pub fn capnode_set_name_flag(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::capnode_set_name_flag(self.r(), idx)?) }
    pub fn capnode_set_b_term_flag(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::capnode_set_b_term_flag(self.r(), idx)?) }
    pub fn capnode_set_i_term_flag(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::capnode_set_i_term_flag(self.r(), idx)?) }
    pub fn capnode_set_internal_flag(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::capnode_set_internal_flag(self.r(), idx)?) }
    pub fn capnode_set_branch_flag(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::capnode_set_branch_flag(self.r(), idx)?) }
    pub fn capnode_set_foreign_flag(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::capnode_set_foreign_flag(self.r(), idx)?) }
    pub fn capnode_set_sort_index(&mut self, idx: usize, a0: u32) -> crate::Result<()> { Ok(sys::capnode_set_sort_index(self.r(), idx, a0)?) }
    pub fn capnode_set_net(&mut self, idx: usize, netid: u32) -> crate::Result<()> { Ok(sys::capnode_set_net(self.r(), idx, netid)?) }
    pub fn capnode_set_next(&mut self, idx: usize, nextid: u32) -> crate::Result<()> { Ok(sys::capnode_set_next(self.r(), idx, nextid)?) }
    pub fn rseg_set_capacitance(&mut self, idx: usize, cap: f64, corner: i32) -> crate::Result<()> { Ok(sys::rseg_set_capacitance(self.r(), idx, cap, corner)?) }
    pub fn rseg_set_resistance(&mut self, idx: usize, res: f64, corner: i32) -> crate::Result<()> { Ok(sys::rseg_set_resistance(self.r(), idx, res, corner)?) }
    pub fn rseg_set_next(&mut self, idx: usize, next_id: u32) -> crate::Result<()> { Ok(sys::rseg_set_next(self.r(), idx, next_id)?) }
    pub fn rseg_set_source_node(&mut self, idx: usize, nodeid: u32) -> crate::Result<()> { Ok(sys::rseg_set_source_node(self.r(), idx, nodeid)?) }
    pub fn rseg_set_target_node(&mut self, idx: usize, nodeid: u32) -> crate::Result<()> { Ok(sys::rseg_set_target_node(self.r(), idx, nodeid)?) }
    pub fn rseg_set_coords(&mut self, idx: usize, x: i32, y: i32) -> crate::Result<()> { Ok(sys::rseg_set_coords(self.r(), idx, x, y)?) }
    pub fn ccseg_set_capacitance(&mut self, idx: usize, cap: f64, corner: i32) -> crate::Result<()> { Ok(sys::ccseg_set_capacitance(self.r(), idx, cap, corner)?) }
    pub fn ccseg_set_mark(&mut self, idx: usize, value: bool) -> crate::Result<()> { Ok(sys::ccseg_set_mark(self.r(), idx, value)?) }
    pub fn sbox_set_via_layer_mask(&mut self, net: &str, swire_idx: usize, sbox_idx: usize, bottom: u32, cut: u32, top: u32) -> crate::Result<()> { Ok(sys::sbox_set_via_layer_mask(self.r(), net, swire_idx, sbox_idx, bottom, cut, top)?) }
    pub fn bpin_set_placement_status(&mut self, bterm: &str, idx: usize, status: &str) -> crate::Result<()> { Ok(sys::bpin_set_placement_status(self.r(), bterm, idx, status)?) }
    pub fn bpin_set_effective_width(&mut self, bterm: &str, idx: usize, w: i32) -> crate::Result<()> { Ok(sys::bpin_set_effective_width(self.r(), bterm, idx, w)?) }
    pub fn bpin_set_min_spacing(&mut self, bterm: &str, idx: usize, w: i32) -> crate::Result<()> { Ok(sys::bpin_set_min_spacing(self.r(), bterm, idx, w)?) }
    pub fn mpin_clear_pin_access(&mut self, master: &str, term: &str, idx: usize, pin_access_idx: i32) -> crate::Result<()> { Ok(sys::mpin_clear_pin_access(self.r(), master, term, idx, pin_access_idx)?) }
    pub fn techvialayerrule_set_width(&mut self, gen_idx: usize, layer_idx: usize, min_width: i32, max_width: i32) -> crate::Result<()> { Ok(sys::techvialayerrule_set_width(self.r(), gen_idx, layer_idx, min_width, max_width)?) }
    pub fn techvialayerrule_set_enclosure(&mut self, gen_idx: usize, layer_idx: usize, overhang1: i32, overhang2: i32) -> crate::Result<()> { Ok(sys::techvialayerrule_set_enclosure(self.r(), gen_idx, layer_idx, overhang1, overhang2)?) }
    pub fn techvialayerrule_set_overhang(&mut self, gen_idx: usize, layer_idx: usize, overhang: i32) -> crate::Result<()> { Ok(sys::techvialayerrule_set_overhang(self.r(), gen_idx, layer_idx, overhang)?) }
    pub fn techvialayerrule_set_metal_overhang(&mut self, gen_idx: usize, layer_idx: usize, overhang: i32) -> crate::Result<()> { Ok(sys::techvialayerrule_set_metal_overhang(self.r(), gen_idx, layer_idx, overhang)?) }
    pub fn techvialayerrule_set_spacing(&mut self, gen_idx: usize, layer_idx: usize, x_spacing: i32, y_spacing: i32) -> crate::Result<()> { Ok(sys::techvialayerrule_set_spacing(self.r(), gen_idx, layer_idx, x_spacing, y_spacing)?) }
    pub fn techvialayerrule_set_resistance(&mut self, gen_idx: usize, layer_idx: usize, r: f64) -> crate::Result<()> { Ok(sys::techvialayerrule_set_resistance(self.r(), gen_idx, layer_idx, r)?) }
    pub fn cutclassrule_set_width(&mut self, layer: &str, idx: usize, width: i32) -> crate::Result<()> { Ok(sys::cutclassrule_set_width(self.r(), layer, idx, width)?) }
    pub fn cutclassrule_set_length(&mut self, layer: &str, idx: usize, length: i32) -> crate::Result<()> { Ok(sys::cutclassrule_set_length(self.r(), layer, idx, length)?) }
    pub fn cutclassrule_set_num_cuts(&mut self, layer: &str, idx: usize, num_cuts: i32) -> crate::Result<()> { Ok(sys::cutclassrule_set_num_cuts(self.r(), layer, idx, num_cuts)?) }
    pub fn cutclassrule_set_length_valid(&mut self, layer: &str, idx: usize, length_valid: bool) -> crate::Result<()> { Ok(sys::cutclassrule_set_length_valid(self.r(), layer, idx, length_valid)?) }
    pub fn cutclassrule_set_cuts_valid(&mut self, layer: &str, idx: usize, cuts_valid: bool) -> crate::Result<()> { Ok(sys::cutclassrule_set_cuts_valid(self.r(), layer, idx, cuts_valid)?) }
    pub fn cutenclosurerule_set_eol_width(&mut self, layer: &str, idx: usize, eol_width: i32) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_eol_width(self.r(), layer, idx, eol_width)?) }
    pub fn cutenclosurerule_set_eol_min_length(&mut self, layer: &str, idx: usize, eol_min_length: i32) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_eol_min_length(self.r(), layer, idx, eol_min_length)?) }
    pub fn cutenclosurerule_set_first_overhang(&mut self, layer: &str, idx: usize, first_overhang: i32) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_first_overhang(self.r(), layer, idx, first_overhang)?) }
    pub fn cutenclosurerule_set_second_overhang(&mut self, layer: &str, idx: usize, second_overhang: i32) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_second_overhang(self.r(), layer, idx, second_overhang)?) }
    pub fn cutenclosurerule_set_spacing(&mut self, layer: &str, idx: usize, spacing: i32) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_spacing(self.r(), layer, idx, spacing)?) }
    pub fn cutenclosurerule_set_extension(&mut self, layer: &str, idx: usize, extension: i32) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_extension(self.r(), layer, idx, extension)?) }
    pub fn cutenclosurerule_set_forward_extension(&mut self, layer: &str, idx: usize, forward_extension: i32) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_forward_extension(self.r(), layer, idx, forward_extension)?) }
    pub fn cutenclosurerule_set_backward_extension(&mut self, layer: &str, idx: usize, backward_extension: i32) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_backward_extension(self.r(), layer, idx, backward_extension)?) }
    pub fn cutenclosurerule_set_min_width(&mut self, layer: &str, idx: usize, min_width: i32) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_min_width(self.r(), layer, idx, min_width)?) }
    pub fn cutenclosurerule_set_cut_within(&mut self, layer: &str, idx: usize, cut_within: i32) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_cut_within(self.r(), layer, idx, cut_within)?) }
    pub fn cutenclosurerule_set_min_length(&mut self, layer: &str, idx: usize, min_length: i32) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_min_length(self.r(), layer, idx, min_length)?) }
    pub fn cutenclosurerule_set_par_length(&mut self, layer: &str, idx: usize, par_length: i32) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_par_length(self.r(), layer, idx, par_length)?) }
    pub fn cutenclosurerule_set_second_par_length(&mut self, layer: &str, idx: usize, second_par_length: i32) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_second_par_length(self.r(), layer, idx, second_par_length)?) }
    pub fn cutenclosurerule_set_par_within(&mut self, layer: &str, idx: usize, par_within: i32) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_par_within(self.r(), layer, idx, par_within)?) }
    pub fn cutenclosurerule_set_second_par_within(&mut self, layer: &str, idx: usize, second_par_within: i32) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_second_par_within(self.r(), layer, idx, second_par_within)?) }
    pub fn cutenclosurerule_set_below_enclosure(&mut self, layer: &str, idx: usize, below_enclosure: i32) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_below_enclosure(self.r(), layer, idx, below_enclosure)?) }
    pub fn cutenclosurerule_set_num_corners(&mut self, layer: &str, idx: usize, num_corners: u32) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_num_corners(self.r(), layer, idx, num_corners)?) }
    pub fn cutenclosurerule_set_cut_class_valid(&mut self, layer: &str, idx: usize, cut_class_valid: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_cut_class_valid(self.r(), layer, idx, cut_class_valid)?) }
    pub fn cutenclosurerule_set_above(&mut self, layer: &str, idx: usize, above: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_above(self.r(), layer, idx, above)?) }
    pub fn cutenclosurerule_set_below(&mut self, layer: &str, idx: usize, below: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_below(self.r(), layer, idx, below)?) }
    pub fn cutenclosurerule_set_eol_min_length_valid(&mut self, layer: &str, idx: usize, eol_min_length_valid: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_eol_min_length_valid(self.r(), layer, idx, eol_min_length_valid)?) }
    pub fn cutenclosurerule_set_eol_only(&mut self, layer: &str, idx: usize, eol_only: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_eol_only(self.r(), layer, idx, eol_only)?) }
    pub fn cutenclosurerule_set_short_edge_on_eol(&mut self, layer: &str, idx: usize, short_edge_on_eol: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_short_edge_on_eol(self.r(), layer, idx, short_edge_on_eol)?) }
    pub fn cutenclosurerule_set_side_spacing_valid(&mut self, layer: &str, idx: usize, side_spacing_valid: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_side_spacing_valid(self.r(), layer, idx, side_spacing_valid)?) }
    pub fn cutenclosurerule_set_end_spacing_valid(&mut self, layer: &str, idx: usize, end_spacing_valid: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_end_spacing_valid(self.r(), layer, idx, end_spacing_valid)?) }
    pub fn cutenclosurerule_set_off_center_line(&mut self, layer: &str, idx: usize, off_center_line: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_off_center_line(self.r(), layer, idx, off_center_line)?) }
    pub fn cutenclosurerule_set_width_valid(&mut self, layer: &str, idx: usize, width_valid: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_width_valid(self.r(), layer, idx, width_valid)?) }
    pub fn cutenclosurerule_set_include_abutted(&mut self, layer: &str, idx: usize, include_abutted: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_include_abutted(self.r(), layer, idx, include_abutted)?) }
    pub fn cutenclosurerule_set_except_extra_cut(&mut self, layer: &str, idx: usize, except_extra_cut: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_except_extra_cut(self.r(), layer, idx, except_extra_cut)?) }
    pub fn cutenclosurerule_set_prl(&mut self, layer: &str, idx: usize, prl: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_prl(self.r(), layer, idx, prl)?) }
    pub fn cutenclosurerule_set_no_shared_edge(&mut self, layer: &str, idx: usize, no_shared_edge: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_no_shared_edge(self.r(), layer, idx, no_shared_edge)?) }
    pub fn cutenclosurerule_set_length_valid(&mut self, layer: &str, idx: usize, length_valid: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_length_valid(self.r(), layer, idx, length_valid)?) }
    pub fn cutenclosurerule_set_extra_cut_valid(&mut self, layer: &str, idx: usize, extra_cut_valid: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_extra_cut_valid(self.r(), layer, idx, extra_cut_valid)?) }
    pub fn cutenclosurerule_set_extra_only(&mut self, layer: &str, idx: usize, extra_only: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_extra_only(self.r(), layer, idx, extra_only)?) }
    pub fn cutenclosurerule_set_redundant_cut_valid(&mut self, layer: &str, idx: usize, redundant_cut_valid: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_redundant_cut_valid(self.r(), layer, idx, redundant_cut_valid)?) }
    pub fn cutenclosurerule_set_parallel_valid(&mut self, layer: &str, idx: usize, parallel_valid: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_parallel_valid(self.r(), layer, idx, parallel_valid)?) }
    pub fn cutenclosurerule_set_second_parallel_valid(&mut self, layer: &str, idx: usize, second_parallel_valid: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_second_parallel_valid(self.r(), layer, idx, second_parallel_valid)?) }
    pub fn cutenclosurerule_set_second_par_within_valid(&mut self, layer: &str, idx: usize, second_par_within_valid: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_second_par_within_valid(self.r(), layer, idx, second_par_within_valid)?) }
    pub fn cutenclosurerule_set_below_enclosure_valid(&mut self, layer: &str, idx: usize, below_enclosure_valid: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_below_enclosure_valid(self.r(), layer, idx, below_enclosure_valid)?) }
    pub fn cutenclosurerule_set_concave_corners_valid(&mut self, layer: &str, idx: usize, concave_corners_valid: bool) -> crate::Result<()> { Ok(sys::cutenclosurerule_set_concave_corners_valid(self.r(), layer, idx, concave_corners_valid)?) }
    pub fn cutspacingrule_set_cut_spacing(&mut self, layer: &str, idx: usize, cut_spacing: i32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_cut_spacing(self.r(), layer, idx, cut_spacing)?) }
    pub fn cutspacingrule_set_orthogonal_spacing(&mut self, layer: &str, idx: usize, orthogonal_spacing: i32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_orthogonal_spacing(self.r(), layer, idx, orthogonal_spacing)?) }
    pub fn cutspacingrule_set_width(&mut self, layer: &str, idx: usize, width: i32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_width(self.r(), layer, idx, width)?) }
    pub fn cutspacingrule_set_enclosure(&mut self, layer: &str, idx: usize, enclosure: i32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_enclosure(self.r(), layer, idx, enclosure)?) }
    pub fn cutspacingrule_set_edge_length(&mut self, layer: &str, idx: usize, edge_length: i32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_edge_length(self.r(), layer, idx, edge_length)?) }
    pub fn cutspacingrule_set_par_within(&mut self, layer: &str, idx: usize, par_within: i32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_par_within(self.r(), layer, idx, par_within)?) }
    pub fn cutspacingrule_set_par_enclosure(&mut self, layer: &str, idx: usize, par_enclosure: i32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_par_enclosure(self.r(), layer, idx, par_enclosure)?) }
    pub fn cutspacingrule_set_edge_enclosure(&mut self, layer: &str, idx: usize, edge_enclosure: i32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_edge_enclosure(self.r(), layer, idx, edge_enclosure)?) }
    pub fn cutspacingrule_set_adj_enclosure(&mut self, layer: &str, idx: usize, adj_enclosure: i32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_adj_enclosure(self.r(), layer, idx, adj_enclosure)?) }
    pub fn cutspacingrule_set_above_enclosure(&mut self, layer: &str, idx: usize, above_enclosure: i32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_above_enclosure(self.r(), layer, idx, above_enclosure)?) }
    pub fn cutspacingrule_set_above_width(&mut self, layer: &str, idx: usize, above_width: i32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_above_width(self.r(), layer, idx, above_width)?) }
    pub fn cutspacingrule_set_min_length(&mut self, layer: &str, idx: usize, min_length: i32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_min_length(self.r(), layer, idx, min_length)?) }
    pub fn cutspacingrule_set_extension(&mut self, layer: &str, idx: usize, extension: i32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_extension(self.r(), layer, idx, extension)?) }
    pub fn cutspacingrule_set_eol_width(&mut self, layer: &str, idx: usize, eol_width: i32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_eol_width(self.r(), layer, idx, eol_width)?) }
    pub fn cutspacingrule_set_num_cuts(&mut self, layer: &str, idx: usize, num_cuts: u32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_num_cuts(self.r(), layer, idx, num_cuts)?) }
    pub fn cutspacingrule_set_within(&mut self, layer: &str, idx: usize, within: i32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_within(self.r(), layer, idx, within)?) }
    pub fn cutspacingrule_set_second_within(&mut self, layer: &str, idx: usize, second_within: i32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_second_within(self.r(), layer, idx, second_within)?) }
    pub fn cutspacingrule_set_two_cuts(&mut self, layer: &str, idx: usize, two_cuts: u32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_two_cuts(self.r(), layer, idx, two_cuts)?) }
    pub fn cutspacingrule_set_prl(&mut self, layer: &str, idx: usize, prl: u32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_prl(self.r(), layer, idx, prl)?) }
    pub fn cutspacingrule_set_par_length(&mut self, layer: &str, idx: usize, par_length: u32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_par_length(self.r(), layer, idx, par_length)?) }
    pub fn cutspacingrule_set_cut_area(&mut self, layer: &str, idx: usize, cut_area: i64) -> crate::Result<()> { Ok(sys::cutspacingrule_set_cut_area(self.r(), layer, idx, cut_area)?) }
    pub fn cutspacingrule_set_center_to_center(&mut self, layer: &str, idx: usize, center_to_center: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_center_to_center(self.r(), layer, idx, center_to_center)?) }
    pub fn cutspacingrule_set_same_net(&mut self, layer: &str, idx: usize, same_net: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_same_net(self.r(), layer, idx, same_net)?) }
    pub fn cutspacingrule_set_same_metal(&mut self, layer: &str, idx: usize, same_metal: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_same_metal(self.r(), layer, idx, same_metal)?) }
    pub fn cutspacingrule_set_same_via(&mut self, layer: &str, idx: usize, same_via: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_same_via(self.r(), layer, idx, same_via)?) }
    pub fn cutspacingrule_set_stack(&mut self, layer: &str, idx: usize, stack: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_stack(self.r(), layer, idx, stack)?) }
    pub fn cutspacingrule_set_orthogonal_spacing_valid(&mut self, layer: &str, idx: usize, orthogonal_spacing_valid: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_orthogonal_spacing_valid(self.r(), layer, idx, orthogonal_spacing_valid)?) }
    pub fn cutspacingrule_set_above_width_enclosure_valid(&mut self, layer: &str, idx: usize, above_width_enclosure_valid: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_above_width_enclosure_valid(self.r(), layer, idx, above_width_enclosure_valid)?) }
    pub fn cutspacingrule_set_short_edge_only(&mut self, layer: &str, idx: usize, short_edge_only: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_short_edge_only(self.r(), layer, idx, short_edge_only)?) }
    pub fn cutspacingrule_set_concave_corner_width(&mut self, layer: &str, idx: usize, concave_corner_width: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_concave_corner_width(self.r(), layer, idx, concave_corner_width)?) }
    pub fn cutspacingrule_set_concave_corner_parallel(&mut self, layer: &str, idx: usize, concave_corner_parallel: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_concave_corner_parallel(self.r(), layer, idx, concave_corner_parallel)?) }
    pub fn cutspacingrule_set_concave_corner_edge_length(&mut self, layer: &str, idx: usize, concave_corner_edge_length: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_concave_corner_edge_length(self.r(), layer, idx, concave_corner_edge_length)?) }
    pub fn cutspacingrule_set_concave_corner(&mut self, layer: &str, idx: usize, concave_corner: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_concave_corner(self.r(), layer, idx, concave_corner)?) }
    pub fn cutspacingrule_set_extension_valid(&mut self, layer: &str, idx: usize, extension_valid: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_extension_valid(self.r(), layer, idx, extension_valid)?) }
    pub fn cutspacingrule_set_non_eol_convex_corner(&mut self, layer: &str, idx: usize, non_eol_convex_corner: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_non_eol_convex_corner(self.r(), layer, idx, non_eol_convex_corner)?) }
    pub fn cutspacingrule_set_eol_width_valid(&mut self, layer: &str, idx: usize, eol_width_valid: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_eol_width_valid(self.r(), layer, idx, eol_width_valid)?) }
    pub fn cutspacingrule_set_min_length_valid(&mut self, layer: &str, idx: usize, min_length_valid: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_min_length_valid(self.r(), layer, idx, min_length_valid)?) }
    pub fn cutspacingrule_set_above_width_valid(&mut self, layer: &str, idx: usize, above_width_valid: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_above_width_valid(self.r(), layer, idx, above_width_valid)?) }
    pub fn cutspacingrule_set_mask_overlap(&mut self, layer: &str, idx: usize, mask_overlap: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_mask_overlap(self.r(), layer, idx, mask_overlap)?) }
    pub fn cutspacingrule_set_wrong_direction(&mut self, layer: &str, idx: usize, wrong_direction: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_wrong_direction(self.r(), layer, idx, wrong_direction)?) }
    pub fn cutspacingrule_set_adjacent_cuts(&mut self, layer: &str, idx: usize, adjacent_cuts: u32) -> crate::Result<()> { Ok(sys::cutspacingrule_set_adjacent_cuts(self.r(), layer, idx, adjacent_cuts)?) }
    pub fn cutspacingrule_set_exact_aligned(&mut self, layer: &str, idx: usize, exact_aligned: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_exact_aligned(self.r(), layer, idx, exact_aligned)?) }
    pub fn cutspacingrule_set_cut_class_to_all(&mut self, layer: &str, idx: usize, cut_class_to_all: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_cut_class_to_all(self.r(), layer, idx, cut_class_to_all)?) }
    pub fn cutspacingrule_set_no_prl(&mut self, layer: &str, idx: usize, no_prl: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_no_prl(self.r(), layer, idx, no_prl)?) }
    pub fn cutspacingrule_set_same_mask(&mut self, layer: &str, idx: usize, same_mask: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_same_mask(self.r(), layer, idx, same_mask)?) }
    pub fn cutspacingrule_set_except_same_pgnet(&mut self, layer: &str, idx: usize, except_same_pgnet: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_except_same_pgnet(self.r(), layer, idx, except_same_pgnet)?) }
    pub fn cutspacingrule_set_side_parallel_overlap(&mut self, layer: &str, idx: usize, side_parallel_overlap: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_side_parallel_overlap(self.r(), layer, idx, side_parallel_overlap)?) }
    pub fn cutspacingrule_set_except_same_net(&mut self, layer: &str, idx: usize, except_same_net: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_except_same_net(self.r(), layer, idx, except_same_net)?) }
    pub fn cutspacingrule_set_except_same_metal(&mut self, layer: &str, idx: usize, except_same_metal: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_except_same_metal(self.r(), layer, idx, except_same_metal)?) }
    pub fn cutspacingrule_set_except_same_metal_overlap(&mut self, layer: &str, idx: usize, except_same_metal_overlap: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_except_same_metal_overlap(self.r(), layer, idx, except_same_metal_overlap)?) }
    pub fn cutspacingrule_set_except_same_via(&mut self, layer: &str, idx: usize, except_same_via: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_except_same_via(self.r(), layer, idx, except_same_via)?) }
    pub fn cutspacingrule_set_above(&mut self, layer: &str, idx: usize, above: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_above(self.r(), layer, idx, above)?) }
    pub fn cutspacingrule_set_except_two_edges(&mut self, layer: &str, idx: usize, except_two_edges: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_except_two_edges(self.r(), layer, idx, except_two_edges)?) }
    pub fn cutspacingrule_set_two_cuts_valid(&mut self, layer: &str, idx: usize, two_cuts_valid: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_two_cuts_valid(self.r(), layer, idx, two_cuts_valid)?) }
    pub fn cutspacingrule_set_same_cut(&mut self, layer: &str, idx: usize, same_cut: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_same_cut(self.r(), layer, idx, same_cut)?) }
    pub fn cutspacingrule_set_long_edge_only(&mut self, layer: &str, idx: usize, long_edge_only: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_long_edge_only(self.r(), layer, idx, long_edge_only)?) }
    pub fn cutspacingrule_set_prl_valid(&mut self, layer: &str, idx: usize, prl_valid: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_prl_valid(self.r(), layer, idx, prl_valid)?) }
    pub fn cutspacingrule_set_below(&mut self, layer: &str, idx: usize, below: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_below(self.r(), layer, idx, below)?) }
    pub fn cutspacingrule_set_par_within_enclosure_valid(&mut self, layer: &str, idx: usize, par_within_enclosure_valid: bool) -> crate::Result<()> { Ok(sys::cutspacingrule_set_par_within_enclosure_valid(self.r(), layer, idx, par_within_enclosure_valid)?) }
    pub fn cutspacingtablerule_set_default(&mut self, layer: &str, idx: usize, spacing: i32) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_default(self.r(), layer, idx, spacing)?) }
    pub fn cutspacingtablerule_set_prl(&mut self, layer: &str, idx: usize, prl: i32) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_prl(self.r(), layer, idx, prl)?) }
    pub fn cutspacingtablerule_set_extension(&mut self, layer: &str, idx: usize, extension: i32) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_extension(self.r(), layer, idx, extension)?) }
    pub fn cutspacingtablerule_set_default_valid(&mut self, layer: &str, idx: usize, default_valid: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_default_valid(self.r(), layer, idx, default_valid)?) }
    pub fn cutspacingtablerule_set_same_mask(&mut self, layer: &str, idx: usize, same_mask: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_same_mask(self.r(), layer, idx, same_mask)?) }
    pub fn cutspacingtablerule_set_same_net(&mut self, layer: &str, idx: usize, same_net: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_same_net(self.r(), layer, idx, same_net)?) }
    pub fn cutspacingtablerule_set_same_metal(&mut self, layer: &str, idx: usize, same_metal: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_same_metal(self.r(), layer, idx, same_metal)?) }
    pub fn cutspacingtablerule_set_same_via(&mut self, layer: &str, idx: usize, same_via: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_same_via(self.r(), layer, idx, same_via)?) }
    pub fn cutspacingtablerule_set_layer_valid(&mut self, layer: &str, idx: usize, layer_valid: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_layer_valid(self.r(), layer, idx, layer_valid)?) }
    pub fn cutspacingtablerule_set_no_stack(&mut self, layer: &str, idx: usize, no_stack: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_no_stack(self.r(), layer, idx, no_stack)?) }
    pub fn cutspacingtablerule_set_non_zero_enclosure(&mut self, layer: &str, idx: usize, non_zero_enclosure: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_non_zero_enclosure(self.r(), layer, idx, non_zero_enclosure)?) }
    pub fn cutspacingtablerule_set_prl_for_aligned_cut(&mut self, layer: &str, idx: usize, prl_for_aligned_cut: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_prl_for_aligned_cut(self.r(), layer, idx, prl_for_aligned_cut)?) }
    pub fn cutspacingtablerule_set_center_to_center_valid(&mut self, layer: &str, idx: usize, center_to_center_valid: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_center_to_center_valid(self.r(), layer, idx, center_to_center_valid)?) }
    pub fn cutspacingtablerule_set_center_and_edge_valid(&mut self, layer: &str, idx: usize, center_and_edge_valid: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_center_and_edge_valid(self.r(), layer, idx, center_and_edge_valid)?) }
    pub fn cutspacingtablerule_set_no_prl(&mut self, layer: &str, idx: usize, no_prl: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_no_prl(self.r(), layer, idx, no_prl)?) }
    pub fn cutspacingtablerule_set_prl_valid(&mut self, layer: &str, idx: usize, prl_valid: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_prl_valid(self.r(), layer, idx, prl_valid)?) }
    pub fn cutspacingtablerule_set_max_x_y(&mut self, layer: &str, idx: usize, max_x_y: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_max_x_y(self.r(), layer, idx, max_x_y)?) }
    pub fn cutspacingtablerule_set_end_extension_valid(&mut self, layer: &str, idx: usize, end_extension_valid: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_end_extension_valid(self.r(), layer, idx, end_extension_valid)?) }
    pub fn cutspacingtablerule_set_side_extension_valid(&mut self, layer: &str, idx: usize, side_extension_valid: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_side_extension_valid(self.r(), layer, idx, side_extension_valid)?) }
    pub fn cutspacingtablerule_set_exact_aligned_spacing_valid(&mut self, layer: &str, idx: usize, exact_aligned_spacing_valid: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_exact_aligned_spacing_valid(self.r(), layer, idx, exact_aligned_spacing_valid)?) }
    pub fn cutspacingtablerule_set_horizontal(&mut self, layer: &str, idx: usize, horizontal: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_horizontal(self.r(), layer, idx, horizontal)?) }
    pub fn cutspacingtablerule_set_prl_horizontal(&mut self, layer: &str, idx: usize, prl_horizontal: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_prl_horizontal(self.r(), layer, idx, prl_horizontal)?) }
    pub fn cutspacingtablerule_set_vertical(&mut self, layer: &str, idx: usize, vertical: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_vertical(self.r(), layer, idx, vertical)?) }
    pub fn cutspacingtablerule_set_prl_vertical(&mut self, layer: &str, idx: usize, prl_vertical: bool) -> crate::Result<()> { Ok(sys::cutspacingtablerule_set_prl_vertical(self.r(), layer, idx, prl_vertical)?) }
    pub fn layerantenna_set_gate_plus_diff_factor(&mut self, layer: &str, factor: f64) -> crate::Result<()> { Ok(sys::layerantenna_set_gate_plus_diff_factor(self.r(), layer, factor)?) }
    pub fn layerantenna_set_area_minus_diff_factor(&mut self, layer: &str, factor: f64) -> crate::Result<()> { Ok(sys::layerantenna_set_area_minus_diff_factor(self.r(), layer, factor)?) }
    pub fn layerantenna_set_area_factor(&mut self, layer: &str, factor: f64, diffuse: bool) -> crate::Result<()> { Ok(sys::layerantenna_set_area_factor(self.r(), layer, factor, diffuse)?) }
    pub fn layerantenna_set_side_area_factor(&mut self, layer: &str, factor: f64, diffuse: bool) -> crate::Result<()> { Ok(sys::layerantenna_set_side_area_factor(self.r(), layer, factor, diffuse)?) }
    pub fn layerantenna_set_antenna_cum_routing_plus_cut(&mut self, layer: &str, value: bool) -> crate::Result<()> { Ok(sys::layerantenna_set_antenna_cum_routing_plus_cut(self.r(), layer, value)?) }
    pub fn layerantenna_set_p_a_r(&mut self, layer: &str, ratio: f64) -> crate::Result<()> { Ok(sys::layerantenna_set_p_a_r(self.r(), layer, ratio)?) }
    pub fn layerantenna_set_c_a_r(&mut self, layer: &str, ratio: f64) -> crate::Result<()> { Ok(sys::layerantenna_set_c_a_r(self.r(), layer, ratio)?) }
    pub fn layerantenna_set_p_s_r(&mut self, layer: &str, ratio: f64) -> crate::Result<()> { Ok(sys::layerantenna_set_p_s_r(self.r(), layer, ratio)?) }
    pub fn layerantenna_set_c_s_r(&mut self, layer: &str, ratio: f64) -> crate::Result<()> { Ok(sys::layerantenna_set_c_s_r(self.r(), layer, ratio)?) }
    pub fn layerantenna_set_diff_p_a_r(&mut self, layer: &str, ratio: f64) -> crate::Result<()> { Ok(sys::layerantenna_set_diff_p_a_r(self.r(), layer, ratio)?) }
    pub fn layerantenna_set_diff_c_a_r(&mut self, layer: &str, ratio: f64) -> crate::Result<()> { Ok(sys::layerantenna_set_diff_c_a_r(self.r(), layer, ratio)?) }
    pub fn layerantenna_set_diff_p_s_r(&mut self, layer: &str, ratio: f64) -> crate::Result<()> { Ok(sys::layerantenna_set_diff_p_s_r(self.r(), layer, ratio)?) }
    pub fn layerantenna_set_diff_c_s_r(&mut self, layer: &str, ratio: f64) -> crate::Result<()> { Ok(sys::layerantenna_set_diff_c_s_r(self.r(), layer, ratio)?) }
    pub fn chip_set_offset(&mut self, chip: &str, x: i32, y: i32) -> crate::Result<()> { Ok(sys::chip_set_offset(self.r(), chip, x, y)?) }
    pub fn chip_set_width(&mut self, chip: &str, width: i32) -> crate::Result<()> { Ok(sys::chip_set_width(self.r(), chip, width)?) }
    pub fn chip_set_height(&mut self, chip: &str, height: i32) -> crate::Result<()> { Ok(sys::chip_set_height(self.r(), chip, height)?) }
    pub fn chip_set_thickness(&mut self, chip: &str, thickness: i32) -> crate::Result<()> { Ok(sys::chip_set_thickness(self.r(), chip, thickness)?) }
    pub fn chip_set_shrink(&mut self, chip: &str, shrink: f32) -> crate::Result<()> { Ok(sys::chip_set_shrink(self.r(), chip, shrink)?) }
    pub fn chip_set_seal_ring_east(&mut self, chip: &str, seal_ring_east: i32) -> crate::Result<()> { Ok(sys::chip_set_seal_ring_east(self.r(), chip, seal_ring_east)?) }
    pub fn chip_set_seal_ring_west(&mut self, chip: &str, seal_ring_west: i32) -> crate::Result<()> { Ok(sys::chip_set_seal_ring_west(self.r(), chip, seal_ring_west)?) }
    pub fn chip_set_seal_ring_north(&mut self, chip: &str, seal_ring_north: i32) -> crate::Result<()> { Ok(sys::chip_set_seal_ring_north(self.r(), chip, seal_ring_north)?) }
    pub fn chip_set_seal_ring_south(&mut self, chip: &str, seal_ring_south: i32) -> crate::Result<()> { Ok(sys::chip_set_seal_ring_south(self.r(), chip, seal_ring_south)?) }
    pub fn chip_set_scribe_line_east(&mut self, chip: &str, scribe_line_east: i32) -> crate::Result<()> { Ok(sys::chip_set_scribe_line_east(self.r(), chip, scribe_line_east)?) }
    pub fn chip_set_scribe_line_west(&mut self, chip: &str, scribe_line_west: i32) -> crate::Result<()> { Ok(sys::chip_set_scribe_line_west(self.r(), chip, scribe_line_west)?) }
    pub fn chip_set_scribe_line_north(&mut self, chip: &str, scribe_line_north: i32) -> crate::Result<()> { Ok(sys::chip_set_scribe_line_north(self.r(), chip, scribe_line_north)?) }
    pub fn chip_set_scribe_line_south(&mut self, chip: &str, scribe_line_south: i32) -> crate::Result<()> { Ok(sys::chip_set_scribe_line_south(self.r(), chip, scribe_line_south)?) }
    pub fn chip_set_tsv(&mut self, chip: &str, tsv: bool) -> crate::Result<()> { Ok(sys::chip_set_tsv(self.r(), chip, tsv)?) }
    pub fn chipinst_set_orient(&mut self, chip: &str, inst: &str, orient: &str) -> crate::Result<()> { Ok(sys::chipinst_set_orient(self.r(), chip, inst, orient)?) }
    pub fn chipinst_set_loc(&mut self, chip: &str, inst: &str, x: i32, y: i32, z: i32) -> crate::Result<()> { Ok(sys::chipinst_set_loc(self.r(), chip, inst, x, y, z)?) }
    pub fn chipconn_set_thickness(&mut self, chip: &str, conn: &str, thickness: i32) -> crate::Result<()> { Ok(sys::chipconn_set_thickness(self.r(), chip, conn, thickness)?) }
}
