// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/generate-bindings.py from docs/derived-core-schema.json -- DO NOT EDIT.
// Machine-generated `Db` SETTERS (L2/write). include!()'d into lib.rs behind `gen-write`.
// &mut self + Result<()>; throws (-> Err) when the addressed object does not exist.

impl Db {
    pub fn block_clear_global_connect(&mut self) -> crate::Result<()> { Ok(sys::block_clear_global_connect(self.r())?) }
    pub fn block_set_def_units(&mut self, units: i32) -> crate::Result<()> { Ok(sys::block_set_def_units(self.r(), units)?) }
    pub fn block_set_corner_name_list(&mut self, name_list: &str) -> crate::Result<()> { Ok(sys::block_set_corner_name_list(self.r(), name_list)?) }
    pub fn block_set_corner_count(&mut self, corner_cnt: i32, ext_db_cnt: i32, name_list: &str) -> crate::Result<()> { Ok(sys::block_set_corner_count(self.r(), corner_cnt, ext_db_cnt, name_list)?) }
    pub fn block_set_min_routing_layer(&mut self, min_routing_layer: i32) -> crate::Result<()> { Ok(sys::block_set_min_routing_layer(self.r(), min_routing_layer)?) }
    pub fn block_set_max_routing_layer(&mut self, max_routing_layer: i32) -> crate::Result<()> { Ok(sys::block_set_max_routing_layer(self.r(), max_routing_layer)?) }
    pub fn block_set_min_layer_for_clock(&mut self, min_layer_for_clock: i32) -> crate::Result<()> { Ok(sys::block_set_min_layer_for_clock(self.r(), min_layer_for_clock)?) }
    pub fn block_set_max_layer_for_clock(&mut self, max_layer_for_clock: i32) -> crate::Result<()> { Ok(sys::block_set_max_layer_for_clock(self.r(), max_layer_for_clock)?) }
    pub fn block_clear(&mut self) -> crate::Result<()> { Ok(sys::block_clear(self.r())?) }
    pub fn block_set_driving_itermsfor_nets(&mut self) -> crate::Result<()> { Ok(sys::block_set_driving_itermsfor_nets(self.r())?) }
    pub fn block_clear_user_inst_flags(&mut self) -> crate::Result<()> { Ok(sys::block_clear_user_inst_flags(self.r())?) }
    pub fn inst_set_origin(&mut self, inst: &str, x: i32, y: i32) -> crate::Result<()> { Ok(sys::inst_set_origin(self.r(), inst, x, y)?) }
    pub fn inst_set_orient(&mut self, inst: &str, orient: &str) -> crate::Result<()> { Ok(sys::inst_set_orient(self.r(), inst, orient)?) }
    pub fn inst_set_location(&mut self, inst: &str, x: i32, y: i32) -> crate::Result<()> { Ok(sys::inst_set_location(self.r(), inst, x, y)?) }
    pub fn inst_set_location_orient(&mut self, inst: &str, orient: &str) -> crate::Result<()> { Ok(sys::inst_set_location_orient(self.r(), inst, orient)?) }
    pub fn inst_set_placement_status(&mut self, inst: &str, status: &str) -> crate::Result<()> { Ok(sys::inst_set_placement_status(self.r(), inst, status)?) }
    pub fn inst_set_eco_create(&mut self, inst: &str, v: bool) -> crate::Result<()> { Ok(sys::inst_set_eco_create(self.r(), inst, v)?) }
    pub fn inst_set_eco_destroy(&mut self, inst: &str, v: bool) -> crate::Result<()> { Ok(sys::inst_set_eco_destroy(self.r(), inst, v)?) }
    pub fn inst_set_eco_modify(&mut self, inst: &str, v: bool) -> crate::Result<()> { Ok(sys::inst_set_eco_modify(self.r(), inst, v)?) }
    pub fn inst_set_user_flag1(&mut self, inst: &str) -> crate::Result<()> { Ok(sys::inst_set_user_flag1(self.r(), inst)?) }
    pub fn inst_clear_user_flag1(&mut self, inst: &str) -> crate::Result<()> { Ok(sys::inst_clear_user_flag1(self.r(), inst)?) }
    pub fn inst_set_user_flag2(&mut self, inst: &str) -> crate::Result<()> { Ok(sys::inst_set_user_flag2(self.r(), inst)?) }
    pub fn inst_clear_user_flag2(&mut self, inst: &str) -> crate::Result<()> { Ok(sys::inst_clear_user_flag2(self.r(), inst)?) }
    pub fn inst_set_user_flag3(&mut self, inst: &str) -> crate::Result<()> { Ok(sys::inst_set_user_flag3(self.r(), inst)?) }
    pub fn inst_clear_user_flag3(&mut self, inst: &str) -> crate::Result<()> { Ok(sys::inst_clear_user_flag3(self.r(), inst)?) }
    pub fn inst_set_do_not_touch(&mut self, inst: &str, v: bool) -> crate::Result<()> { Ok(sys::inst_set_do_not_touch(self.r(), inst, v)?) }
    pub fn inst_set_halo(&mut self, inst: &str, left: i32, bottom: i32, right: i32, top: i32, is_soft: bool) -> crate::Result<()> { Ok(sys::inst_set_halo(self.r(), inst, left, bottom, right, top, is_soft)?) }
    pub fn inst_set_weight(&mut self, inst: &str, weight: i32) -> crate::Result<()> { Ok(sys::inst_set_weight(self.r(), inst, weight)?) }
    pub fn inst_set_source_type(&mut self, inst: &str, a0: &str) -> crate::Result<()> { Ok(sys::inst_set_source_type(self.r(), inst, a0)?) }
    pub fn inst_set_pin_access_idx(&mut self, inst: &str, idx: u32) -> crate::Result<()> { Ok(sys::inst_set_pin_access_idx(self.r(), inst, idx)?) }
    pub fn net_set_r_c_disconnected(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_r_c_disconnected(self.r(), net, value)?) }
    pub fn net_set_weight(&mut self, net: &str, weight: i32) -> crate::Result<()> { Ok(sys::net_set_weight(self.r(), net, weight)?) }
    pub fn net_set_source_type(&mut self, net: &str, a0: &str) -> crate::Result<()> { Ok(sys::net_set_source_type(self.r(), net, a0)?) }
    pub fn net_set_x_talk_class(&mut self, net: &str, value: i32) -> crate::Result<()> { Ok(sys::net_set_x_talk_class(self.r(), net, value)?) }
    pub fn net_set_fixed_bump(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_fixed_bump(self.r(), net, value)?) }
    pub fn net_set_wire_type(&mut self, net: &str, wire_type: &str) -> crate::Result<()> { Ok(sys::net_set_wire_type(self.r(), net, wire_type)?) }
    pub fn net_set_sig_type(&mut self, net: &str, sig_type: &str) -> crate::Result<()> { Ok(sys::net_set_sig_type(self.r(), net, sig_type)?) }
    pub fn net_set_mark(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_mark(self.r(), net, value)?) }
    pub fn net_set_mark_1(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_mark_1(self.r(), net, value)?) }
    pub fn net_set_select(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_select(self.r(), net, value)?) }
    pub fn net_set_wire_ordered(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_wire_ordered(self.r(), net, value)?) }
    pub fn net_set_disconnected(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_disconnected(self.r(), net, value)?) }
    pub fn net_set_wire_altered(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_wire_altered(self.r(), net, value)?) }
    pub fn net_set_r_cgraph(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_r_cgraph(self.r(), net, value)?) }
    pub fn net_set_extracted(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_extracted(self.r(), net, value)?) }
    pub fn net_set_spef(&mut self, net: &str, value: bool) -> crate::Result<()> { Ok(sys::net_set_spef(self.r(), net, value)?) }
    pub fn net_set_do_not_touch(&mut self, net: &str, v: bool) -> crate::Result<()> { Ok(sys::net_set_do_not_touch(self.r(), net, v)?) }
    pub fn net_set_special(&mut self, net: &str) -> crate::Result<()> { Ok(sys::net_set_special(self.r(), net)?) }
    pub fn net_clear_special(&mut self, net: &str) -> crate::Result<()> { Ok(sys::net_clear_special(self.r(), net)?) }
    pub fn net_set_i_oflag(&mut self, net: &str) -> crate::Result<()> { Ok(sys::net_set_i_oflag(self.r(), net)?) }
    pub fn net_set_wild_connected(&mut self, net: &str) -> crate::Result<()> { Ok(sys::net_set_wild_connected(self.r(), net)?) }
    pub fn net_clear_wild_connected(&mut self, net: &str) -> crate::Result<()> { Ok(sys::net_clear_wild_connected(self.r(), net)?) }
    pub fn net_set_gndc_calib_factor(&mut self, net: &str, gndc_calib: f32) -> crate::Result<()> { Ok(sys::net_set_gndc_calib_factor(self.r(), net, gndc_calib)?) }
    pub fn net_set_cc_calib_factor(&mut self, net: &str, cc_calib: f32) -> crate::Result<()> { Ok(sys::net_set_cc_calib_factor(self.r(), net, cc_calib)?) }
    pub fn net_set_cc_adjust_factor(&mut self, net: &str, factor: f32) -> crate::Result<()> { Ok(sys::net_set_cc_adjust_factor(self.r(), net, factor)?) }
    pub fn net_set_cc_adjust_order(&mut self, net: &str, order: u32) -> crate::Result<()> { Ok(sys::net_set_cc_adjust_order(self.r(), net, order)?) }
    pub fn net_set_db_cc(&mut self, net: &str, cap: f32) -> crate::Result<()> { Ok(sys::net_set_db_cc(self.r(), net, cap)?) }
    pub fn net_set_ref_cc(&mut self, net: &str, cap: f32) -> crate::Result<()> { Ok(sys::net_set_ref_cc(self.r(), net, cap)?) }
    pub fn net_set_cc_match_ratio(&mut self, net: &str, ratio: f32) -> crate::Result<()> { Ok(sys::net_set_cc_match_ratio(self.r(), net, ratio)?) }
    pub fn net_set1st_r_seg_id(&mut self, net: &str, rseg_id: u32) -> crate::Result<()> { Ok(sys::net_set1st_r_seg_id(self.r(), net, rseg_id)?) }
    pub fn net_set1st_cap_node_id(&mut self, net: &str, capn_id: u32) -> crate::Result<()> { Ok(sys::net_set1st_cap_node_id(self.r(), net, capn_id)?) }
    pub fn net_set_term_ext_ids(&mut self, net: &str, cap_id: i32) -> crate::Result<()> { Ok(sys::net_set_term_ext_ids(self.r(), net, cap_id)?) }
    pub fn net_clear_guides(&mut self, net: &str) -> crate::Result<()> { Ok(sys::net_clear_guides(self.r(), net)?) }
    pub fn net_clear_tracks(&mut self, net: &str) -> crate::Result<()> { Ok(sys::net_clear_tracks(self.r(), net)?) }
    pub fn net_set_jumpers(&mut self, net: &str, has_jumpers: bool) -> crate::Result<()> { Ok(sys::net_set_jumpers(self.r(), net, has_jumpers)?) }
    pub fn bterm_set_sig_type(&mut self, bterm: &str, a0: &str) -> crate::Result<()> { Ok(sys::bterm_set_sig_type(self.r(), bterm, a0)?) }
    pub fn bterm_set_io_type(&mut self, bterm: &str, a0: &str) -> crate::Result<()> { Ok(sys::bterm_set_io_type(self.r(), bterm, a0)?) }
    pub fn bterm_set_spef_mark(&mut self, bterm: &str, v: u32) -> crate::Result<()> { Ok(sys::bterm_set_spef_mark(self.r(), bterm, v)?) }
    pub fn bterm_set_mark(&mut self, bterm: &str, v: u32) -> crate::Result<()> { Ok(sys::bterm_set_mark(self.r(), bterm, v)?) }
    pub fn bterm_set_ext_id(&mut self, bterm: &str, v: u32) -> crate::Result<()> { Ok(sys::bterm_set_ext_id(self.r(), bterm, v)?) }
    pub fn bterm_set_special(&mut self, bterm: &str) -> crate::Result<()> { Ok(sys::bterm_set_special(self.r(), bterm)?) }
    pub fn master_set_origin(&mut self, master: &str, x: i32, y: i32) -> crate::Result<()> { Ok(sys::master_set_origin(self.r(), master, x, y)?) }
    pub fn master_set_width(&mut self, master: &str, width: u32) -> crate::Result<()> { Ok(sys::master_set_width(self.r(), master, width)?) }
    pub fn master_set_height(&mut self, master: &str, height: u32) -> crate::Result<()> { Ok(sys::master_set_height(self.r(), master, height)?) }
    pub fn master_set_backside_bridge(&mut self, master: &str, is_bridge: bool) -> crate::Result<()> { Ok(sys::master_set_backside_bridge(self.r(), master, is_bridge)?) }
    pub fn master_set_symmetry_x(&mut self, master: &str) -> crate::Result<()> { Ok(sys::master_set_symmetry_x(self.r(), master)?) }
    pub fn master_set_symmetry_y(&mut self, master: &str) -> crate::Result<()> { Ok(sys::master_set_symmetry_y(self.r(), master)?) }
    pub fn master_set_symmetry_r90(&mut self, master: &str) -> crate::Result<()> { Ok(sys::master_set_symmetry_r90(self.r(), master)?) }
    pub fn master_set_frozen(&mut self, master: &str) -> crate::Result<()> { Ok(sys::master_set_frozen(self.r(), master)?) }
    pub fn master_set_sequential(&mut self, master: &str, v: bool) -> crate::Result<()> { Ok(sys::master_set_sequential(self.r(), master, v)?) }
    pub fn master_set_mark(&mut self, master: &str, mark: u32) -> crate::Result<()> { Ok(sys::master_set_mark(self.r(), master, mark)?) }
    pub fn master_set_special_power(&mut self, master: &str, v: bool) -> crate::Result<()> { Ok(sys::master_set_special_power(self.r(), master, v)?) }
    pub fn master_clear_pin_access(&mut self, master: &str, pin_access_idx: i32) -> crate::Result<()> { Ok(sys::master_clear_pin_access(self.r(), master, pin_access_idx)?) }
    pub fn iterm_set_spef(&mut self, inst: &str, pin: &str, v: u32) -> crate::Result<()> { Ok(sys::iterm_set_spef(self.r(), inst, pin, v)?) }
    pub fn iterm_set_ext_id(&mut self, inst: &str, pin: &str, v: u32) -> crate::Result<()> { Ok(sys::iterm_set_ext_id(self.r(), inst, pin, v)?) }
    pub fn iterm_set_special(&mut self, inst: &str, pin: &str) -> crate::Result<()> { Ok(sys::iterm_set_special(self.r(), inst, pin)?) }
    pub fn iterm_clear_special(&mut self, inst: &str, pin: &str) -> crate::Result<()> { Ok(sys::iterm_clear_special(self.r(), inst, pin)?) }
    pub fn iterm_set_clocked(&mut self, inst: &str, pin: &str, v: bool) -> crate::Result<()> { Ok(sys::iterm_set_clocked(self.r(), inst, pin, v)?) }
    pub fn iterm_set_mark(&mut self, inst: &str, pin: &str, v: u32) -> crate::Result<()> { Ok(sys::iterm_set_mark(self.r(), inst, pin, v)?) }
    pub fn iterm_set_connected(&mut self, inst: &str, pin: &str) -> crate::Result<()> { Ok(sys::iterm_set_connected(self.r(), inst, pin)?) }
    pub fn iterm_clear_connected(&mut self, inst: &str, pin: &str) -> crate::Result<()> { Ok(sys::iterm_clear_connected(self.r(), inst, pin)?) }
    pub fn iterm_clear_pref_access_points(&mut self, inst: &str, pin: &str) -> crate::Result<()> { Ok(sys::iterm_clear_pref_access_points(self.r(), inst, pin)?) }
    pub fn mterm_set_sig_type(&mut self, master: &str, term: &str, a0: &str) -> crate::Result<()> { Ok(sys::mterm_set_sig_type(self.r(), master, term, a0)?) }
    pub fn mterm_set_mark(&mut self, master: &str, term: &str, v: u32) -> crate::Result<()> { Ok(sys::mterm_set_mark(self.r(), master, term, v)?) }
    pub fn layer_set_wrong_way_width(&mut self, layer: &str, wrong_way_width: u32) -> crate::Result<()> { Ok(sys::layer_set_wrong_way_width(self.r(), layer, wrong_way_width)?) }
    pub fn layer_set_wrong_way_min_width(&mut self, layer: &str, wrong_way_min_width: u32) -> crate::Result<()> { Ok(sys::layer_set_wrong_way_min_width(self.r(), layer, wrong_way_min_width)?) }
    pub fn layer_set_layer_adjustment(&mut self, layer: &str, layer_adjustment: f32) -> crate::Result<()> { Ok(sys::layer_set_layer_adjustment(self.r(), layer, layer_adjustment)?) }
    pub fn layer_set_rect_only(&mut self, layer: &str, rect_only: bool) -> crate::Result<()> { Ok(sys::layer_set_rect_only(self.r(), layer, rect_only)?) }
    pub fn layer_set_right_way_on_grid_only(&mut self, layer: &str, right_way_on_grid_only: bool) -> crate::Result<()> { Ok(sys::layer_set_right_way_on_grid_only(self.r(), layer, right_way_on_grid_only)?) }
    pub fn layer_set_right_way_on_grid_only_check_mask(&mut self, layer: &str, right_way_on_grid_only_check_mask: bool) -> crate::Result<()> { Ok(sys::layer_set_right_way_on_grid_only_check_mask(self.r(), layer, right_way_on_grid_only_check_mask)?) }
    pub fn layer_set_rect_only_except_non_core_pins(&mut self, layer: &str, rect_only_except_non_core_pins: bool) -> crate::Result<()> { Ok(sys::layer_set_rect_only_except_non_core_pins(self.r(), layer, rect_only_except_non_core_pins)?) }
    pub fn layer_set_backside(&mut self, layer: &str, is_backside: bool) -> crate::Result<()> { Ok(sys::layer_set_backside(self.r(), layer, is_backside)?) }
    pub fn layer_set_alias(&mut self, layer: &str, alias: &str) -> crate::Result<()> { Ok(sys::layer_set_alias(self.r(), layer, alias)?) }
    pub fn layer_set_width(&mut self, layer: &str, width: i32) -> crate::Result<()> { Ok(sys::layer_set_width(self.r(), layer, width)?) }
    pub fn layer_set_spacing(&mut self, layer: &str, spacing: i32) -> crate::Result<()> { Ok(sys::layer_set_spacing(self.r(), layer, spacing)?) }
    pub fn layer_set_num_masks(&mut self, layer: &str, number: u32) -> crate::Result<()> { Ok(sys::layer_set_num_masks(self.r(), layer, number)?) }
    pub fn layer_set_pitch(&mut self, layer: &str, pitch: i32) -> crate::Result<()> { Ok(sys::layer_set_pitch(self.r(), layer, pitch)?) }
    pub fn layer_set_pitch_x_y(&mut self, layer: &str, pitch_x: i32, pitch_y: i32) -> crate::Result<()> { Ok(sys::layer_set_pitch_x_y(self.r(), layer, pitch_x, pitch_y)?) }
    pub fn layer_set_first_last_pitch(&mut self, layer: &str, first_last_pitch: i32) -> crate::Result<()> { Ok(sys::layer_set_first_last_pitch(self.r(), layer, first_last_pitch)?) }
    pub fn layer_set_offset(&mut self, layer: &str, pitch: i32) -> crate::Result<()> { Ok(sys::layer_set_offset(self.r(), layer, pitch)?) }
    pub fn layer_set_offset_x_y(&mut self, layer: &str, pitch_x: i32, pitch_y: i32) -> crate::Result<()> { Ok(sys::layer_set_offset_x_y(self.r(), layer, pitch_x, pitch_y)?) }
    pub fn layer_set_thickness(&mut self, layer: &str, thickness: u32) -> crate::Result<()> { Ok(sys::layer_set_thickness(self.r(), layer, thickness)?) }
    pub fn layer_set_area(&mut self, layer: &str, area: i64) -> crate::Result<()> { Ok(sys::layer_set_area(self.r(), layer, area)?) }
    pub fn layer_set_max_width(&mut self, layer: &str, max_width: u32) -> crate::Result<()> { Ok(sys::layer_set_max_width(self.r(), layer, max_width)?) }
    pub fn layer_set_min_width(&mut self, layer: &str, max_width: u32) -> crate::Result<()> { Ok(sys::layer_set_min_width(self.r(), layer, max_width)?) }
    pub fn layer_set_min_step(&mut self, layer: &str, min_step: u32) -> crate::Result<()> { Ok(sys::layer_set_min_step(self.r(), layer, min_step)?) }
    pub fn layer_set_min_step_max_length(&mut self, layer: &str, length: u32) -> crate::Result<()> { Ok(sys::layer_set_min_step_max_length(self.r(), layer, length)?) }
    pub fn layer_set_min_step_max_edges(&mut self, layer: &str, edges: u32) -> crate::Result<()> { Ok(sys::layer_set_min_step_max_edges(self.r(), layer, edges)?) }
    pub fn layer_set_resistance(&mut self, layer: &str, res: f64) -> crate::Result<()> { Ok(sys::layer_set_resistance(self.r(), layer, res)?) }
    pub fn layer_set_capacitance(&mut self, layer: &str, cap: f64) -> crate::Result<()> { Ok(sys::layer_set_capacitance(self.r(), layer, cap)?) }
    pub fn layer_set_edge_capacitance(&mut self, layer: &str, cap: f64) -> crate::Result<()> { Ok(sys::layer_set_edge_capacitance(self.r(), layer, cap)?) }
    pub fn layer_set_wire_extension(&mut self, layer: &str, ext: u32) -> crate::Result<()> { Ok(sys::layer_set_wire_extension(self.r(), layer, ext)?) }
    pub fn via_set_pattern(&mut self, via: &str, pattern: &str) -> crate::Result<()> { Ok(sys::via_set_pattern(self.r(), via, pattern)?) }
    pub fn techvia_set_default(&mut self, via: &str) -> crate::Result<()> { Ok(sys::techvia_set_default(self.r(), via)?) }
    pub fn techvia_set_top_of_stack(&mut self, via: &str) -> crate::Result<()> { Ok(sys::techvia_set_top_of_stack(self.r(), via)?) }
    pub fn techvia_set_resistance(&mut self, via: &str, res: f64) -> crate::Result<()> { Ok(sys::techvia_set_resistance(self.r(), via, res)?) }
    pub fn techvia_set_pattern(&mut self, via: &str, pattern: &str) -> crate::Result<()> { Ok(sys::techvia_set_pattern(self.r(), via, pattern)?) }
    pub fn ndr_set_hard_spacing(&mut self, rule: &str, value: bool) -> crate::Result<()> { Ok(sys::ndr_set_hard_spacing(self.r(), rule, value)?) }
    pub fn site_set_width(&mut self, site: &str, width: i32) -> crate::Result<()> { Ok(sys::site_set_width(self.r(), site, width)?) }
    pub fn site_set_height(&mut self, site: &str, height: i32) -> crate::Result<()> { Ok(sys::site_set_height(self.r(), site, height)?) }
    pub fn site_set_symmetry_x(&mut self, site: &str) -> crate::Result<()> { Ok(sys::site_set_symmetry_x(self.r(), site)?) }
    pub fn site_set_symmetry_y(&mut self, site: &str) -> crate::Result<()> { Ok(sys::site_set_symmetry_y(self.r(), site)?) }
    pub fn site_set_symmetry_r90(&mut self, site: &str) -> crate::Result<()> { Ok(sys::site_set_symmetry_r90(self.r(), site)?) }
    pub fn obs_set_slot_obstruction(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::obs_set_slot_obstruction(self.r(), idx)?) }
    pub fn obs_set_fill_obstruction(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::obs_set_fill_obstruction(self.r(), idx)?) }
    pub fn obs_set_except_p_g_nets_obstruction(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::obs_set_except_p_g_nets_obstruction(self.r(), idx)?) }
    pub fn obs_set_pushed_down(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::obs_set_pushed_down(self.r(), idx)?) }
    pub fn obs_set_effective_width(&mut self, idx: usize, w: i32) -> crate::Result<()> { Ok(sys::obs_set_effective_width(self.r(), idx, w)?) }
    pub fn obs_set_min_spacing(&mut self, idx: usize, w: i32) -> crate::Result<()> { Ok(sys::obs_set_min_spacing(self.r(), idx, w)?) }
    pub fn obs_set_is_system_reserved(&mut self, idx: usize, is_system_reserved: bool) -> crate::Result<()> { Ok(sys::obs_set_is_system_reserved(self.r(), idx, is_system_reserved)?) }
    pub fn swire_set_wire_type(&mut self, net: &str, idx: usize, a0: &str) -> crate::Result<()> { Ok(sys::swire_set_wire_type(self.r(), net, idx, a0)?) }
    pub fn wire_set_property(&mut self, net: &str, jid: i32, property: i32) -> crate::Result<()> { Ok(sys::wire_set_property(self.r(), net, jid, property)?) }
    pub fn box_set_soft(&mut self, idx: usize, value: bool) -> crate::Result<()> { Ok(sys::box_set_soft(self.r(), idx, value)?) }
    pub fn box_set_layer_mask(&mut self, idx: usize, mask: u32) -> crate::Result<()> { Ok(sys::box_set_layer_mask(self.r(), idx, mask)?) }
    pub fn region_set_invalid(&mut self, region: &str, v: bool) -> crate::Result<()> { Ok(sys::region_set_invalid(self.r(), region, v)?) }
    pub fn blockage_set_pushed_down(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::blockage_set_pushed_down(self.r(), idx)?) }
    pub fn blockage_set_soft(&mut self, idx: usize) -> crate::Result<()> { Ok(sys::blockage_set_soft(self.r(), idx)?) }
    pub fn blockage_set_is_system_reserved(&mut self, idx: usize, is_system_reserved: bool) -> crate::Result<()> { Ok(sys::blockage_set_is_system_reserved(self.r(), idx, is_system_reserved)?) }
    pub fn blockage_set_max_density(&mut self, idx: usize, max_density: f32) -> crate::Result<()> { Ok(sys::blockage_set_max_density(self.r(), idx, max_density)?) }
    pub fn marker_cat_set_description(&mut self, category: &str, description: &str) -> crate::Result<()> { Ok(sys::marker_cat_set_description(self.r(), category, description)?) }
    pub fn marker_cat_set_source(&mut self, category: &str, source: &str) -> crate::Result<()> { Ok(sys::marker_cat_set_source(self.r(), category, source)?) }
    pub fn marker_cat_set_max_markers(&mut self, category: &str, max_markers: i32) -> crate::Result<()> { Ok(sys::marker_cat_set_max_markers(self.r(), category, max_markers)?) }
    pub fn marker_set_comment(&mut self, category: &str, idx: usize, comment: &str) -> crate::Result<()> { Ok(sys::marker_set_comment(self.r(), category, idx, comment)?) }
    pub fn marker_set_line_number(&mut self, category: &str, idx: usize, line_number: i32) -> crate::Result<()> { Ok(sys::marker_set_line_number(self.r(), category, idx, line_number)?) }
    pub fn marker_set_visited(&mut self, category: &str, idx: usize, visited: bool) -> crate::Result<()> { Ok(sys::marker_set_visited(self.r(), category, idx, visited)?) }
    pub fn marker_set_visible(&mut self, category: &str, idx: usize, visible: bool) -> crate::Result<()> { Ok(sys::marker_set_visible(self.r(), category, idx, visible)?) }
    pub fn marker_set_waived(&mut self, category: &str, idx: usize, waived: bool) -> crate::Result<()> { Ok(sys::marker_set_waived(self.r(), category, idx, waived)?) }
    pub fn pwr_domain_set_top(&mut self, name: &str, top: bool) -> crate::Result<()> { Ok(sys::pwr_domain_set_top(self.r(), name, top)?) }
    pub fn pwr_domain_set_voltage(&mut self, name: &str, voltage: f32) -> crate::Result<()> { Ok(sys::pwr_domain_set_voltage(self.r(), name, voltage)?) }
    pub fn pwr_switch_set_out_supply_port(&mut self, name: &str, out_port: &str, net: &str) -> crate::Result<()> { Ok(sys::pwr_switch_set_out_supply_port(self.r(), name, out_port, net)?) }
    pub fn isolation_set_applies_to(&mut self, name: &str, applies_to: &str) -> crate::Result<()> { Ok(sys::isolation_set_applies_to(self.r(), name, applies_to)?) }
    pub fn isolation_set_clamp_value(&mut self, name: &str, clamp_value: &str) -> crate::Result<()> { Ok(sys::isolation_set_clamp_value(self.r(), name, clamp_value)?) }
    pub fn isolation_set_isolation_signal(&mut self, name: &str, isolation_signal: &str) -> crate::Result<()> { Ok(sys::isolation_set_isolation_signal(self.r(), name, isolation_signal)?) }
    pub fn isolation_set_isolation_sense(&mut self, name: &str, isolation_sense: &str) -> crate::Result<()> { Ok(sys::isolation_set_isolation_sense(self.r(), name, isolation_sense)?) }
    pub fn isolation_set_location(&mut self, name: &str, location: &str) -> crate::Result<()> { Ok(sys::isolation_set_location(self.r(), name, location)?) }
    pub fn level_shifter_set_source(&mut self, name: &str, source: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_source(self.r(), name, source)?) }
    pub fn level_shifter_set_sink(&mut self, name: &str, sink: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_sink(self.r(), name, sink)?) }
    pub fn level_shifter_set_use_functional_equivalence(&mut self, name: &str, use_functional_equivalence: bool) -> crate::Result<()> { Ok(sys::level_shifter_set_use_functional_equivalence(self.r(), name, use_functional_equivalence)?) }
    pub fn level_shifter_set_applies_to(&mut self, name: &str, applies_to: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_applies_to(self.r(), name, applies_to)?) }
    pub fn level_shifter_set_applies_to_boundary(&mut self, name: &str, applies_to_boundary: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_applies_to_boundary(self.r(), name, applies_to_boundary)?) }
    pub fn level_shifter_set_rule(&mut self, name: &str, rule: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_rule(self.r(), name, rule)?) }
    pub fn level_shifter_set_threshold(&mut self, name: &str, threshold: f32) -> crate::Result<()> { Ok(sys::level_shifter_set_threshold(self.r(), name, threshold)?) }
    pub fn level_shifter_set_no_shift(&mut self, name: &str, no_shift: bool) -> crate::Result<()> { Ok(sys::level_shifter_set_no_shift(self.r(), name, no_shift)?) }
    pub fn level_shifter_set_force_shift(&mut self, name: &str, force_shift: bool) -> crate::Result<()> { Ok(sys::level_shifter_set_force_shift(self.r(), name, force_shift)?) }
    pub fn level_shifter_set_location(&mut self, name: &str, location: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_location(self.r(), name, location)?) }
    pub fn level_shifter_set_input_supply(&mut self, name: &str, input_supply: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_input_supply(self.r(), name, input_supply)?) }
    pub fn level_shifter_set_output_supply(&mut self, name: &str, output_supply: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_output_supply(self.r(), name, output_supply)?) }
    pub fn level_shifter_set_internal_supply(&mut self, name: &str, internal_supply: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_internal_supply(self.r(), name, internal_supply)?) }
    pub fn level_shifter_set_name_prefix(&mut self, name: &str, name_prefix: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_name_prefix(self.r(), name, name_prefix)?) }
    pub fn level_shifter_set_name_suffix(&mut self, name: &str, name_suffix: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_name_suffix(self.r(), name, name_suffix)?) }
    pub fn level_shifter_set_cell_name(&mut self, name: &str, cell_name: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_cell_name(self.r(), name, cell_name)?) }
    pub fn level_shifter_set_cell_input(&mut self, name: &str, cell_input: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_cell_input(self.r(), name, cell_input)?) }
    pub fn level_shifter_set_cell_output(&mut self, name: &str, cell_output: &str) -> crate::Result<()> { Ok(sys::level_shifter_set_cell_output(self.r(), name, cell_output)?) }
}
